---
title: "Figure 5A"
author: "Melissa Spear"
date: "21/07/2020"
output: html_document
---


```{r}
a = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T, sep='\t')

#install.packages("RColorBrewer")
require(RColorBrewer)

###Stratified height plots
a$CENTER2=as.factor(a$CENTER)
#plotting height as a function of birthyear 
Lowest_NAM=a[which(a$NAM>=0.01 & a$NAM<0.37),]
Lower_NAM=a[which(a$NAM>=0.37 & a$NAM<0.46),]
Moderate_NAM=a[which(a$NAM>=0.46 & a$NAM<=0.58),]
High_NAM=a[which(a$NAM>0.58),]


Lowest_NAM$native_level="4"
Lower_NAM$native_level="3"
Moderate_NAM$native_level="2"
High_NAM$native_level="1"

all_levels=rbind(Lowest_NAM,Lower_NAM,Moderate_NAM,High_NAM)

mypalette2<-brewer.pal(9,"BuPu")

```


```{r}
Lowest_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=Lowest_NAM)
Lower_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=Lower_NAM)
Moderate_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=Moderate_NAM)
High_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=High_NAM)
all_groups_center <- lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=all_levels)
```



```{r}
###############################
#Paper - plotting height as a fucntion of birth year 
#adjusting by center
par(mfrow=c(1,1))


#same plot as above but different color palette
pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper/figures/HCHS_SOL_Mexican_Height_estimated_birth_year_NAM_ancestry_stratified_102119_diffcolors_figure_4B.pdf",height=2.25,width=2.375,pointsize=10)
par(mar=c(2.1,2.1,0.1,0.1))
plot(1,1,type='n',xlim=range(all_levels$estimated_birth_year),ylim=c(115,200),xlab="",ylab="",xaxt='n',yaxt='n')
abline(h=seq(120,200,by=10),col=rgb(0,0,0,0.1))
abline(v=seq(1930,2000,by=5),col=rgb(0,0,0,0.1))
axis(side=1,padj=-2,cex.axis=0.7)
axis(side=2,padj=1.5,cex.axis=0.7)
mtext(side=1,"Birth year",line=1.1)
mtext(side=2,"Height (cm)",line=1.1)
#plot(a$estimated_birth_year,a$HEIGHT,xlab="Birth year", ylab="Height(cm)")
points(all_levels$estimated_birth_year,all_levels$HEIGHT,pch=20,cex=0.8)
points(Lowest_NAM$estimated_birth_year,Lowest_NAM$HEIGHT,col=mypalette2[3],pch=20,cex=0.8)
points(Lower_NAM$estimated_birth_year,Lower_NAM$HEIGHT,col=mypalette2[5],pch=20,cex=0.8)
points(Moderate_NAM$estimated_birth_year,Moderate_NAM$HEIGHT,col=mypalette2[6],pch=20,cex=0.8)
points(High_NAM$estimated_birth_year,High_NAM$HEIGHT,col=mypalette2[8],pch=20,cex=0.8)
lines(x = 1934:1993, y = coefficients(Lowest_model_center)[1] + coefficients(Lowest_model_center)[2]* (1934:1993),col ="white",lwd = 4)
lines(x = 1934:1993, y = coefficients(Lowest_model_center)[1] + coefficients(Lowest_model_center)[2]* (1934:1993),col =mypalette2[3],lwd = 3)


lines(x = 1934:1993, y = coefficients(Lower_model_center)[1] + coefficients(Lower_model_center)[2]* (1934:1993), col = "white",lwd = 4)
lines(x = 1934:1993, y = coefficients(Lower_model_center)[1] + coefficients(Lower_model_center)[2]* (1934:1993), col = mypalette2[5],lwd = 3)


lines(x = 1934:1993, y = coefficients(Moderate_model_center)[1] + coefficients(Moderate_model_center)[2]* (1934:1993), col ="white",lwd = 4)
lines(x = 1934:1993, y = coefficients(Moderate_model_center)[1] + coefficients(Moderate_model_center)[2]* (1934:1993), col =mypalette2[6],lwd = 3)


lines(x = 1934:1993, y = coefficients(High_model_center)[1] + coefficients(High_model_center)[2]* (1934:1993), col = "white",lwd = 4)
lines(x = 1934:1993, y = coefficients(High_model_center)[1] + coefficients(High_model_center)[2]* (1934:1993), col = mypalette2[8],lwd = 3)

lines(x = 1934:1993, y = coefficients(all_groups_center)[1] + coefficients(all_groups_center)[2]* (1934:1993), col = "white",lwd = 4)
lines(x = 1934:1993, y = coefficients(all_groups_center)[1] + coefficients(all_groups_center)[2]* (1934:1993), col = "black",lwd = 3)

legend("bottomright", legend=c("0.01<AI<0.37","0.37<AI<0.46","0.46<AI<0.58","0.58<AI","All"),
       col=c(mypalette2[3],mypalette2[5],mypalette2[6],mypalette2[8],"black"), bg="white",lty=1, lwd=2,cex=0.4)

dev.off()



```
