---
title: "HCHS/SOL ROH analyses"
author: "Melissa Spear"
date: "15/05/2020"
output: html_document
---

The following code plots AI and CEU tracts 

AI tracts 
```{r}
#read in summed ROH calls 
ai_roh_calls<-read.table("/Volumes/LaCie/Downloads/split_roh_files/NAM_ROH_segments/reclassified_classes/summed_calls2/HCHS_SOL_Mexicans_alldecades_summed_NAM_ROH_calls_newclasses_080519.txt",header=F,sep='\t')

#adding column titles 
names(ai_roh_calls)=c("IID","ROH_A","ROH_B","ROH_C")

#3570 samples made the cut - some samples do not have NAM roh. 

#read in pheno file 
d = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T,sep='\t')

#subset for needed variables
pheno_subsetted<-subset(d,select=c("V1","V2","US_BORN","estimated_birth_year","WEIGHT_FINAL_NORM_OVERALL"))

#merge with pheno file 
ai_roh_with_pheno<-merge(ai_roh_calls,pheno_subsetted,by.x=("IID"),by.y=c("V2"))
```


```{r}
#Read in the admixture file estimates file 
HCHS_SOL_admixture_file<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.3.Q", header =F, sep = ' ')
names(HCHS_SOL_admixture_file) <- c("YRI","CEU","AI")

#Reading in the fam file accompaniment of the .bed file called for the admixture run 
fam_file = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.fam", header=F, sep = ' ')
names(fam_file)<-c("FID","IID","PID","MID","Sex","Pheno")
fam_file_with_IDs <- cbind(fam_file, HCHS_SOL_admixture_file)

##merge with admixture estimates 
ai_roh_with_pheno_admixture<-merge(ai_roh_with_pheno,fam_file_with_IDs, by.x=c("IID"),by.y=c("IID"))

#Calcualting AI genome length 
ai_roh_with_pheno_admixture$AI_both_haps_length<- (ai_roh_with_pheno_admixture$AI * 5563642548)
```

```{r}
#some samples do not have roh in some classes and will cause errors in the analysis pipeline so added roh of 1 BP long to all samples to fill in 0s.  
ai_roh_with_pheno_admixture$ROH_A<-ai_roh_with_pheno_admixture$ROH_A+1
ai_roh_with_pheno_admixture$ROH_B<-ai_roh_with_pheno_admixture$ROH_B+1
ai_roh_with_pheno_admixture$ROH_C<-ai_roh_with_pheno_admixture$ROH_C+1

#creating new variable summing three ROH columns 
ai_roh_with_pheno_admixture$ROH_allclasses_sums<- rowSums(ai_roh_with_pheno_admixture[,c("ROH_A", "ROH_B","ROH_C")])

#normalizing ALL ROH by global ancestry 
ai_roh_with_pheno_admixture$ROH_allclasses_sums_NORM<-(ai_roh_with_pheno_admixture$ROH_allclasses_sums)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

#normalizing short ROH by global ancestry 
ai_roh_with_pheno_admixture$ROH_A_NORM<-(ai_roh_with_pheno_admixture$ROH_A)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

#normalizing medium ROH by global ancestry 
ai_roh_with_pheno_admixture$ROH_B_NORM<-(ai_roh_with_pheno_admixture$ROH_B)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

#normalizing long ROH by global ancestry 
ai_roh_with_pheno_admixture$ROH_C_NORM<-(ai_roh_with_pheno_admixture$ROH_C)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

#proportion of genome covered in ROH 
ai_roh_with_pheno_admixture$prop_genome_AI_ROH<-(ai_roh_with_pheno_admixture$ROH_allclasses_sums_NORM * 2781821274)
```


CEU tracts 

```{r}
#read in summed ROH calls 
ceu_roh_calls<-read.table("/Volumes/LaCie/Downloads/split_roh_files/CEU_ROH_segments/reclassified_classes/summed_calls/HCHS_SOL_Mexicans_alldecades_summed_CEU_ROH_calls_newclasses_051520.txt",header=F,sep='\t')

#adding column titles 
names(ceu_roh_calls)=c("IID","ROH_A","ROH_B","ROH_C")

#merge with pheno file 
ceu_roh_with_pheno<-merge(ceu_roh_calls,pheno_subsetted,by.x=("IID"),by.y=c("V2"))
```


```{r}
#merge with admixture estimates 
ceu_roh_with_pheno_admixture<-merge(ceu_roh_with_pheno,fam_file_with_IDs, by.x=c("IID"),by.y=c("IID"))

#Calcualting AI genome length 
ceu_roh_with_pheno_admixture$CEU_both_haps_length<- (ceu_roh_with_pheno_admixture$CEU * 5563642548)
```

```{r}
#some samples do not have roh in some classes and will cause errors in the analysis pipeline so added roh of 1 BP long to all samples to fill in 0s.  
ceu_roh_with_pheno_admixture$ROH_A<-ceu_roh_with_pheno_admixture$ROH_A+1
ceu_roh_with_pheno_admixture$ROH_B<-ceu_roh_with_pheno_admixture$ROH_B+1
ceu_roh_with_pheno_admixture$ROH_C<-ceu_roh_with_pheno_admixture$ROH_C+1


#creating new variable summing three ROH columns 
ceu_roh_with_pheno_admixture$ROH_allclasses_sums<- rowSums(ceu_roh_with_pheno_admixture[,c("ROH_A", "ROH_B","ROH_C")])

#normalizing ALL ROH by global ancestry 
ceu_roh_with_pheno_admixture$ROH_allclasses_sums_NORM<-(ceu_roh_with_pheno_admixture$ROH_allclasses_sums)/((ceu_roh_with_pheno_admixture$CEU_both_haps_length)/(2)) 

#normalizing short ROH by global ancestry 
ceu_roh_with_pheno_admixture$ROH_A_NORM<-(ceu_roh_with_pheno_admixture$ROH_A)/((ceu_roh_with_pheno_admixture$CEU_both_haps_length)/(2)) 

#normalizing medium ROH by global ancestry 
ceu_roh_with_pheno_admixture$ROH_B_NORM<-(ceu_roh_with_pheno_admixture$ROH_B)/((ceu_roh_with_pheno_admixture$CEU_both_haps_length)/(2)) 

#normalizing long ROH by global ancestry 
ceu_roh_with_pheno_admixture$ROH_C_NORM<-(ceu_roh_with_pheno_admixture$ROH_C)/((ceu_roh_with_pheno_admixture$CEU_both_haps_length)/(2)) 

#proportion of genome covered in ROH -- following normalization? actual BP 
ceu_roh_with_pheno_admixture$prop_genome_CEU_ROH<-(ceu_roh_with_pheno_admixture$ROH_allclasses_sums_NORM * 2781821274)
```


#Plot figure 
```{r}
#pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures/Mexicans_norm_ROH_CEU_AI_alltracts_052620_new_figure3C.pdf",height=2.25,width=2.375,pointsize=10)
par(mar=c(2.1,2.1,0.3,0.25))
plot(1,1,type='n',xlim=c(1934, 1993),ylim=c(0,0.04),xlab="",ylab="",xaxt='n',yaxt='n')
abline(h=seq(0,0.04,by=0.01),col=rgb(0,0,0,0.1))
abline(v=seq(1930,2000,by=10),col=rgb(0,0,0,0.1))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90)
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.90)
mtext(side=1,"Birth year",line=1.1)
mtext(side=2,"Proportion of genome with ROH",line=1.0,cex.lab=0.6)

legend("topleft",ncol=2,legend=c("All AI ROH","All Short AI ROH","All Medium AI ROH", "All Long AI ROH", "All CEU ROH","All Short CEU ROH","All Medium CEU ROH","All Long CEU ROH"), col=c("black","#D95F02","#7570B3","#E7298A","black","#D95F02","#7570B3","#E7298A"),lty=c(1,1,1,1,3,3,3,3),cex=0.4,bg="white")


#CEU all ROH 
lw1 <- loess(ROH_allclasses_sums_NORM ~ estimated_birth_year,data=ceu_roh_with_pheno_admixture)
j1 <- order(ceu_roh_with_pheno_admixture$estimated_birth_year)
lines(ceu_roh_with_pheno_admixture$estimated_birth_year[j1],lw1$fitted[j1],col="black",lwd=1,lty=3)
#AI all
lw1_ai <- loess(ROH_allclasses_sums_NORM ~ estimated_birth_year,data=ai_roh_with_pheno_admixture)
j1_ai <- order(ai_roh_with_pheno_admixture$estimated_birth_year)
lines(ai_roh_with_pheno_admixture$estimated_birth_year[j1_ai],lw1_ai$fitted[j1_ai],col="black",lwd=1)
#CEU long ROH 
lw2 <- loess(ROH_C_NORM ~ estimated_birth_year,data=ceu_roh_with_pheno_admixture)
j2 <- order(ceu_roh_with_pheno_admixture$estimated_birth_year)
lines(ceu_roh_with_pheno_admixture$estimated_birth_year[j2],lw2$fitted[j2],col="#E7298A",lwd=1,lty=3)
#AI long roh
lw2_ai <- loess(ROH_C_NORM ~ estimated_birth_year,data=ai_roh_with_pheno_admixture)
j2_ai <- order(ai_roh_with_pheno_admixture$estimated_birth_year)
lines(ai_roh_with_pheno_admixture$estimated_birth_year[j2_ai],lw2_ai$fitted[j2_ai],col="#E7298A",lwd=1)
#CEU medium ROH 
lw3 <- loess(ROH_B_NORM ~ estimated_birth_year,data=ceu_roh_with_pheno_admixture)
j3 <- order(ceu_roh_with_pheno_admixture$estimated_birth_year)
lines(ceu_roh_with_pheno_admixture$estimated_birth_year[j3],lw3$fitted[j3],col="#7570B3",lwd=1,lty=3)
#AI medium roh
lw3_ai <- loess(ROH_B_NORM ~ estimated_birth_year,data=ai_roh_with_pheno_admixture)
j3_ai <- order(ai_roh_with_pheno_admixture$estimated_birth_year)
lines(ai_roh_with_pheno_admixture$estimated_birth_year[j3_ai],lw3_ai$fitted[j3_ai],col="#7570B3",lwd=1)
#all CEU short ROH 
lw4 <- loess(ROH_A_NORM ~ estimated_birth_year,data=ceu_roh_with_pheno_admixture)
j4 <- order(ceu_roh_with_pheno_admixture$estimated_birth_year)
lines(ceu_roh_with_pheno_admixture$estimated_birth_year[j4],lw4$fitted[j4],col="#D95F02",lwd=1,lty=3)
#all short ROH -nam 
lw4_ai <- loess(ROH_A_NORM ~ estimated_birth_year,data=ai_roh_with_pheno_admixture)
j4_ai<- order(ai_roh_with_pheno_admixture$estimated_birth_year)
lines(ai_roh_with_pheno_admixture$estimated_birth_year[j4_ai],lw4_ai$fitted[j4_ai],col="#D95F02",lwd=1)

#dev.off()

```


#####
Statistical Analyses supporting figure 3C 
Correlation between normalized ROH proportion and birth year

```{r}
#all tracts 
cor.test(ai_roh_with_pheno_admixture$ROH_allclasses_sums_NORM, ai_roh_with_pheno_admixture$estimated_birth_year,method="kendall")
```

```{r}
#short ROH tracts 
cor.test(ai_roh_with_pheno_admixture$ROH_A_NORM, ai_roh_with_pheno_admixture$estimated_birth_year,method="kendall")
```

```{r}
#medium ROH tracts 
cor.test(ai_roh_with_pheno_admixture$ROH_B_NORM, ai_roh_with_pheno_admixture$estimated_birth_year,method="kendall")
```

```{r}
#long ROH tracts 
cor.test(ai_roh_with_pheno_admixture$ROH_C_NORM, ai_roh_with_pheno_admixture$estimated_birth_year,method="kendall")
```


CEU ROH analyses 

```{r}
#all tracts 
cor.test(ceu_roh_with_pheno_admixture$ROH_allclasses_sums_NORM, ceu_roh_with_pheno_admixture$estimated_birth_year,method="kendall")
```
