---
title: "Figure 3B"
author: "Melissa Spear"
date: "13/05/2020"
output: html_document
---

```{r}
#AI ancestry plots- changes in proportiosn for Mexicans.
##This plot uses base R grahpics to plot the paper verison of the figure


#######################
# This plots the proportion change in log scale of NAM ancestral tract

library("reshape2")
innameTRACTS.1990 = paste('/Users/melissaspear/Dropbox/HCHS_SOL/tracts_proportions/1990s/boot0.bins.data.txt', sep="")
MX_1990s = read.table(innameTRACTS.1990, header= T, check.names=F)
Pop_dataframe <-data.frame(Pop = c("NAM", "CEU", "YRI")) #the order of these labels is based on the order they were put into tracts 
MX_1990s_merged <- cbind(MX_1990s, Pop_dataframe)
MX_1990_reshaped = melt(MX_1990s_merged) #melts the dataset into a plot able dataset
MX_1990_reshaped$variable100 = as.numeric(as.character(MX_1990_reshaped$variable)) *100 #scales the x axis variable in order to march tracts plots of cM. Right now just in M
MX.1990.NAM = MX_1990_reshaped[which(MX_1990_reshaped$Pop == 'NAM'),]
MX.1990.CEU = MX_1990_reshaped[which(MX_1990_reshaped$Pop == 'CEU'),]
MX.1990.YRI = MX_1990_reshaped[which(MX_1990_reshaped$Pop == 'YRI'),]
#summing the number or tracts total and calculating the proportion with propotion being out of TOTAL NUMBER OF TRACTS
MX.1990.NAM$prop = MX.1990.NAM$value/sum(MX.1990.NAM$value)
MX.1990.CEU$prop = MX.1990.CEU$value/sum(MX.1990.CEU$value)
MX.1990.YRI$prop = MX.1990.YRI$value/sum(MX.1990.YRI$value)
#MX.1990.NAM$prop2 <- log(MX.1990.NAM$prop)
#MX.1990.CEU$prop2 <- log(MX.1990.CEU$prop)
#MX.1990.YRI$prop2 <- log(MX.1990.YRI$prop)

#this replaces any 0s? Not too sure....
MX.1990.NAM <- do.call(data.frame, lapply(MX.1990.NAM, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1990.CEU <- do.call(data.frame, lapply(MX.1990.CEU, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1990.YRI <- do.call(data.frame, lapply(MX.1990.YRI, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1990.NAM_no0s = MX.1990.NAM[which(MX.1990.NAM$prop!='0'),]

#1980s
innameTRACTS.1980 = paste('/Users/melissaspear/Dropbox/HCHS_SOL/tracts_proportions/1980s/boot0.bins.data.txt', sep="")
MX_1980s = read.table(innameTRACTS.1980, header= T, check.names=F)
MX_1980s_merged <- cbind(MX_1980s, Pop_dataframe)
MX_1980_reshaped = melt(MX_1980s_merged) #melts the dataset into a plot able dataset
MX_1980_reshaped$variable100 = as.numeric(as.character(MX_1980_reshaped$variable)) *100 #scales the x axis variable in order to march tracts plots of cM
MX.1980.NAM = MX_1980_reshaped[which(MX_1980_reshaped$Pop == 'NAM'),]
MX.1980.CEU = MX_1980_reshaped[which(MX_1980_reshaped$Pop == 'CEU'),]
MX.1980.YRI = MX_1980_reshaped[which(MX_1980_reshaped$Pop == 'YRI'),]
MX.1980.NAM$prop = MX.1980.NAM$value/sum(MX.1980.NAM$value)
MX.1980.CEU$prop = MX.1980.CEU$value/sum(MX.1980.CEU$value)
MX.1980.YRI$prop = MX.1980.YRI$value/sum(MX.1980.YRI$value)
#MX.1980.NAM$prop2 <- log(MX.1980.NAM$prop)
#MX.1980.CEU$prop2 <- log(MX.1980.CEU$prop)
#MX.1980.YRI$prop2 <- log(MX.1980.YRI$prop)
MX.1980.NAM <- do.call(data.frame, lapply(MX.1980.NAM, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1980.CEU <- do.call(data.frame, lapply(MX.1980.CEU, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1980.YRI <- do.call(data.frame, lapply(MX.1980.YRI, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1980.NAM_no0s = MX.1980.NAM[which(MX.1980.NAM$prop!='0'),]

#1970s
innameTRACTS.1970 = paste('/Users/melissaspear/Dropbox/HCHS_SOL/tracts_proportions/1970s/boot0.bins.data.txt', sep="")
MX_1970s = read.table(innameTRACTS.1970, header= T, check.names=F)
MX_1970s_merged <- cbind(MX_1970s, Pop_dataframe)
MX_1970_reshaped = melt(MX_1970s_merged) #melts the dataset into a plot able dataset
MX_1970_reshaped$variable100 = as.numeric(as.character(MX_1970_reshaped$variable)) *100 #scales the x axis variable in order to march tracts plots of cM
MX.1970.NAM = MX_1970_reshaped[which(MX_1970_reshaped$Pop == 'NAM'),]
MX.1970.CEU = MX_1970_reshaped[which(MX_1970_reshaped$Pop == 'CEU'),]
MX.1970.YRI = MX_1970_reshaped[which(MX_1970_reshaped$Pop == 'YRI'),]
MX.1970.NAM$prop = MX.1970.NAM$value/sum(MX.1970.NAM$value)
MX.1970.CEU$prop = MX.1970.CEU$value/sum(MX.1970.CEU$value)
MX.1970.YRI$prop = MX.1970.YRI$value/sum(MX.1970.YRI$value)
#MX.1970.NAM$prop2 <- log(MX.1970.NAM$prop)
#MX.1970.CEU$prop2 <- log(MX.1970.CEU$prop)
#MX.1970.YRI$prop2 <- log(MX.1970.YRI$prop)
MX.1970.NAM <- do.call(data.frame, lapply(MX.1970.NAM, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1970.CEU <- do.call(data.frame, lapply(MX.1970.CEU, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1970.YRI <- do.call(data.frame, lapply(MX.1970.YRI, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1970.NAM_no0s = MX.1970.NAM[which(MX.1970.NAM$prop!='0'),]

#1960s
innameTRACTS.1960 = paste('/Users/melissaspear/Dropbox/HCHS_SOL/tracts_proportions/1960s/boot0.bins.data.txt', sep="")
MX_1960s = read.table(innameTRACTS.1960, header= T, check.names=F)
MX_1960s_merged <- cbind(MX_1960s, Pop_dataframe)
MX_1960_reshaped = melt(MX_1960s_merged) #melts the dataset into a plot able dataset
MX_1960_reshaped$variable100 = as.numeric(as.character(MX_1960_reshaped$variable)) *100 #scales the x axis variable in order to march tracts plots of cM
MX.1960.NAM = MX_1960_reshaped[which(MX_1960_reshaped$Pop == 'NAM'),]
MX.1960.CEU = MX_1960_reshaped[which(MX_1960_reshaped$Pop == 'CEU'),]
MX.1960.YRI = MX_1960_reshaped[which(MX_1960_reshaped$Pop == 'YRI'),]
MX.1960.NAM$prop = MX.1960.NAM$value/sum(MX.1960.NAM$value)
MX.1960.CEU$prop = MX.1960.CEU$value/sum(MX.1960.CEU$value)
MX.1960.YRI$prop = MX.1960.YRI$value/sum(MX.1960.YRI$value)
#MX.1960.NAM$prop2 <- log(MX.1960.NAM$prop)
#MX.1960.CEU$prop2 <- log(MX.1960.CEU$prop)
#MX.1960.YRI$prop2 <- log(MX.1960.YRI$prop)
MX.1960.NAM <- do.call(data.frame, lapply(MX.1960.NAM, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1960.CEU <- do.call(data.frame, lapply(MX.1960.CEU, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1960.YRI <- do.call(data.frame, lapply(MX.1960.YRI, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1960.NAM_no0s = MX.1960.NAM[which(MX.1960.NAM$prop!='0'),]

#1950s
innameTRACTS.1950 = paste('/Users/melissaspear/Dropbox/HCHS_SOL/tracts_proportions/1950s/boot0.bins.data.txt', sep="")
MX_1950s = read.table(innameTRACTS.1950, header= T, check.names=F)
MX_1950s_merged <- cbind(MX_1950s, Pop_dataframe)
MX_1950_reshaped = melt(MX_1950s_merged) #melts the dataset into a plot able dataset
MX_1950_reshaped$variable100 = as.numeric(as.character(MX_1950_reshaped$variable)) *100 #scales the x axis variable in order to march tracts plots of cM
MX.1950.NAM = MX_1950_reshaped[which(MX_1950_reshaped$Pop == 'NAM'),]
MX.1950.CEU = MX_1950_reshaped[which(MX_1950_reshaped$Pop == 'CEU'),]
MX.1950.YRI = MX_1950_reshaped[which(MX_1950_reshaped$Pop == 'YRI'),]
MX.1950.NAM$prop = MX.1950.NAM$value/sum(MX.1950.NAM$value)
MX.1950.CEU$prop = MX.1950.CEU$value/sum(MX.1950.CEU$value)
MX.1950.YRI$prop = MX.1950.YRI$value/sum(MX.1950.YRI$value)
#MX.1950.NAM$prop2 <- log(MX.1950.NAM$prop)
#MX.1950.CEU$prop2 <- log(MX.1950.CEU$prop)
#MX.1950.YRI$prop2 <- log(MX.1950.YRI$prop)
MX.1950.NAM <- do.call(data.frame, lapply(MX.1950.NAM, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1950.CEU <- do.call(data.frame, lapply(MX.1950.CEU, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1950.YRI <- do.call(data.frame, lapply(MX.1950.YRI, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1950.NAM_no0s = MX.1950.NAM[which(MX.1950.NAM$prop!='0'),]

#1940s
innameTRACTS.1940 = paste('/Users/melissaspear/Dropbox/HCHS_SOL/tracts_proportions/1940s/boot0.bins.data.txt', sep="")
MX_1940s = read.table(innameTRACTS.1940, header= T, check.names=F)
MX_1940s_merged <- cbind(MX_1940s, Pop_dataframe)
MX_1940_reshaped = melt(MX_1940s_merged) #melts the dataset into a plot able dataset
MX_1940_reshaped$variable100 = as.numeric(as.character(MX_1940_reshaped$variable)) *100 #scales the x axis variable in order to march tracts plots of cM
MX.1940.NAM = MX_1940_reshaped[which(MX_1940_reshaped$Pop == 'NAM'),]
MX.1940.CEU = MX_1940_reshaped[which(MX_1940_reshaped$Pop == 'CEU'),]
MX.1940.YRI = MX_1940_reshaped[which(MX_1940_reshaped$Pop == 'YRI'),]
MX.1940.NAM$prop = MX.1940.NAM$value/sum(MX.1940.NAM$value)
MX.1940.CEU$prop = MX.1940.CEU$value/sum(MX.1940.CEU$value)
MX.1940.YRI$prop = MX.1940.YRI$value/sum(MX.1940.YRI$value)
#MX.1940.NAM$prop2 <- log(MX.1940.NAM$prop)
#MX.1940.CEU$prop2 <- log(MX.1940.CEU$prop)
#MX.1940.YRI$prop2 <- log(MX.1940.YRI$prop)
MX.1940.NAM <- do.call(data.frame, lapply(MX.1940.NAM, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1940.CEU <- do.call(data.frame, lapply(MX.1940.CEU, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1940.YRI <- do.call(data.frame, lapply(MX.1940.YRI, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1940.NAM_no0s = MX.1940.NAM[which(MX.1940.NAM$prop!='0'),]

#1930s
innameTRACTS.1930 = paste('/Users/melissaspear/Dropbox/HCHS_SOL/tracts_proportions/1930s/boot0.bins.data.txt', sep="")
MX_1930s = read.table(innameTRACTS.1930, header= T, check.names=F)
MX_1930s_merged <- cbind(MX_1930s, Pop_dataframe)
MX_1930_reshaped = melt(MX_1930s_merged) #melts the dataset into a plot able dataset
MX_1930_reshaped$variable100 = as.numeric(as.character(MX_1930_reshaped$variable)) *100 #scales the x axis variable in order to march tracts plots of cM
MX.1930.NAM = MX_1930_reshaped[which(MX_1930_reshaped$Pop == 'NAM'),]
MX.1930.CEU = MX_1930_reshaped[which(MX_1930_reshaped$Pop == 'CEU'),]
MX.1930.YRI = MX_1930_reshaped[which(MX_1930_reshaped$Pop == 'YRI'),]
MX.1930.NAM$prop = MX.1930.NAM$value/sum(MX.1930.NAM$value)
MX.1930.CEU$prop = MX.1930.CEU$value/sum(MX.1930.CEU$value)
MX.1930.YRI$prop = MX.1930.YRI$value/sum(MX.1930.YRI$value)
#MX.1930.NAM$prop2 <- log(MX.1930.NAM$prop)
#MX.1930.CEU$prop2 <- log(MX.1930.CEU$prop)
#MX.1930.YRI$prop2 <- log(MX.1930.YRI$prop)
MX.1930.NAM <- do.call(data.frame, lapply(MX.1930.NAM, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1930.CEU <- do.call(data.frame, lapply(MX.1930.CEU, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1930.YRI <- do.call(data.frame, lapply(MX.1930.YRI, function(x) {replace(x, is.infinite(x) | is.na(x), 0)}))
MX.1930.NAM_no0s = MX.1930.NAM[which(MX.1930.NAM$prop!='0'),]

all_NAM_decades = rbind(MX.1930.NAM, MX.1940.NAM, MX.1950.NAM, MX.1960.NAM, MX.1970.NAM, MX.1980.NAM, MX.1990.NAM)
all_CEU_decades = rbind(MX.1930.CEU, MX.1940.CEU, MX.1950.CEU, MX.1960.CEU, MX.1970.CEU, MX.1980.CEU, MX.1990.CEU)
all_YRI_decades = rbind(MX.1930.YRI, MX.1940.YRI, MX.1950.YRI, MX.1960.YRI, MX.1970.YRI, MX.1980.YRI, MX.1990.YRI)

```

Plot figure 
```{r}

#plot with tranparetn points 
require(RColorBrewer)
myColors=brewer.pal(7, "Set1")

t_col <- function(color, percent = 50, name = NULL) {
  #      color = color name
  #    percent = % transparency
  #       name = an optional name for the color

## Get RGB values for named color
rgb.val <- col2rgb(color)

## Make new color using input color as base and alpha set by transparency
t.col <- rgb(rgb.val[1], rgb.val[2], rgb.val[3],
             max = 255,
             alpha = (100 - percent) * 255 / 100,
             names = name)

## Save the color
invisible(t.col)
}

red_trans=t_col("#E41A1C", perc = 50, name = "lt.red")
orange_trans=t_col("#FF7F00", perc = 50, name = "lt.orange")
yellow_trans=t_col("#FFFF33", perc = 50, name = "lt.yellow")
green_trans=t_col("#4DAF4A", perc = 50, name = "lt.green")
blue_trans=t_col("#377EB8", perc = 50, name = "lt.blue")
purple_trans=t_col("#984EA3", perc = 50, name = "lt.purple")
brown_trans=t_col("#A65628", perc = 50, name = "lt.brown")

#pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper/figures/Mexicans_NAM_ancestral_tracts_proportion_change_log_scale_071619_Figure_3B_new.pdf",height=2.25,width=2.375,pointsize=10)
par(mar=c(2.1,3.25,0.25,0.35))
plot(prop~variable100,type='n',data=all_NAM_decades,pch=19,log="y",xlab="",ylab="",xaxt='n',yaxt='n', alpha=0.5)
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted")
#abline(h=seq(0,300,by=0.1),col=rgb(0,0,0,0.1))
#abline(v=seq(0,300,by=50),col=rgb(0,0,0,0.1))
axis(side=1,padj=-2,cex.axis=0.7,cex.lab=0.9)
axis(side=2,las=1,at=c("1e-05","1e-04","1e-03","1e-02","1e-01"),labels=c(expression(paste("10"^"-5")),expression(paste("10"^"-4")),expression(paste("10"^"-3")),expression(paste("10"^"-2")),expression(paste("10"^"-1"))),hadj=0.55,padj=0.25,cex.axis=0.7,cex.lab=0.9)
mtext(side=1,"tract length (cM)",line=1.15,cex.lab=0.8)
mtext(side=2,expression(log[10]("Proportion of total ")),line=2.15,cex.lab=0.8)
mtext(side=2,"AI ancestral tracts)",line=1.55,cex.lab=0.8)
points(prop~variable100,data=MX.1930.NAM,pch=21,col=red_trans, bg=red_trans,cex=0.75)
points(prop~variable100,data=MX.1940.NAM,pch=21,col=orange_trans,bg=orange_trans,cex=0.75)
points(prop~variable100,data=MX.1950.NAM,pch=21,col=yellow_trans,bg=yellow_trans,cex=0.75)
points(prop~variable100,data=MX.1960.NAM,pch=21,col=green_trans,bg=green_trans,cex=0.75)
points(prop~variable100,data=MX.1970.NAM,pch=21,col=blue_trans,bg=blue_trans,cex=0.75)
points(prop~variable100,data=MX.1980.NAM,pch=21,col=purple_trans,bg=purple_trans,cex=0.75)
points(prop~variable100,data=MX.1990.NAM,pch=21,col=brown_trans,bg=brown_trans,cex=0.75)
legend("bottomleft",legend=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"),col=c(red_trans,orange_trans,yellow_trans,green_trans,blue_trans,purple_trans,brown_trans),pch=19,cex =0.75,bg="white")
#dev.off()
```



Testing the models 