---
title: "Figure 5C"
author: "Melissa Spear"
date: "21/07/2020"
output: html_document
---

Supplementary Figure 11 - PRS as a function of birthyear 


```{r}
###Plotting PRS based on 1 Mb distance SNPs, stratifed by ancestry 
pheno_file<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T, sep='\t')

PRS_phys<-read.table("/Volumes/LaCie/Downloads/PRS/HCHS_SOLMexicans_090120_UKBB_snps_individual_polygenic_height_scores_phys_distance_1Mb_filter_TEST2.txt")
names(PRS_phys)<-c("FID","IID","risk_score")
merged_data_phys<-merge(PRS_phys,pheno_file,by.x=("FID"),by.y=c("V1"))


#setting "Center" variable as factor so R knows how to use it in model 
merged_data_phys$CENTER2<-as.factor(merged_data_phys$CENTER)

merged_data_phys$Education<-as.factor(merged_data_phys$EDUCATION_C3)

merged_data_phys$num_us_parents <- with(merged_data_phys,
                         ifelse(PIEA14=='63' & PIEA11=='63',2,
                            ifelse(PIEA14!='63' & PIEA11!='63',0,1)))
merged_data_phys$num_us_parents<-as.numeric(merged_data_phys$num_us_parents)


#Dividing dataset 
Lowest_NAM <- merged_data_phys[which(merged_data_phys$NAM>=0.01 & merged_data_phys$NAM<0.37),]
Lower_NAM <- merged_data_phys[which(merged_data_phys$NAM>=0.37 & merged_data_phys$NAM<0.46),]
Moderate_NAM <- merged_data_phys[which(merged_data_phys$NAM>=0.46 & merged_data_phys$NAM<=0.58),]
High_NAM <- merged_data_phys[which(merged_data_phys$NAM>0.58),]

highest_NAM_half<-merged_data_phys[which(merged_data_phys$NAM>0.46),]

Lowest_NAM$native_level="4"
Lower_NAM$native_level="3"
Moderate_NAM$native_level="2"
High_NAM$native_level="1"

all_levels<-rbind(Lowest_NAM,Lower_NAM,Moderate_NAM,High_NAM)

```


```{r}
# Setting model for each stratified dataset - No effect of birth year/age on PRS. 
Lowest_model_center <- lm(risk_score~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=Lowest_NAM)
Lower_model_center <- lm(risk_score~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=Lower_NAM)
Moderate_model_center <- lm(risk_score~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=Moderate_NAM)
High_model_center <- lm(risk_score~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=High_NAM)
all_groups_center <- lm(risk_score~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=all_levels)
```


```{r}
# Plot 
mypalette<-brewer.pal(5,"Set1")
mypalette2<-brewer.pal(9,"BuPu")

par(mfrow=c(1,1))
#pdf("/Users/melissaspear/Dropbox/HCHS_SOL/PRS/phys_distance_1Mb/plots/HCHS_SOL_Mexican_PRS_estimated_birth_year_NAM_ancestry_stratified_041219.pdf",height=5.00,width=6,pointsize=9)
pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper/figures/supplementary_figure11_102520_with_environment.pdf",height=2.25,width=2.375,pointsize=10)
par(mar=c(2.1,2.1,0.1,0.1))
plot(1,1,type='n',xlim=range(merged_data_phys$estimated_birth_year),ylim=c(-1,1),xlab="",ylab="",xaxt='n',yaxt='n')
abline(h=seq(-1,1,by=0.5),col=rgb(0,0,0,0.1))
abline(v=seq(1930,2000,by=5),col=rgb(0,0,0,0.1))
axis(side=1,padj=-2,cex.axis=0.7)
axis(side=2,padj=1.5,cex.axis=0.7)
mtext(side=1,"Birth year",line=1.1)
mtext(side=2,"Polygenic height score (cm)",line=1.1)
#grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted")
points(merged_data_phys$estimated_birth_year,merged_data_phys$risk_score,pch=20,cex=0.8)
points(Lowest_NAM$estimated_birth_year,Lowest_NAM$risk_score,col=mypalette2[3],pch=20,cex=0.8)
points(Lower_NAM$estimated_birth_year,Lower_NAM$risk_score,col=mypalette2[5],pch=20,cex=0.8)
points(Moderate_NAM$estimated_birth_year,Moderate_NAM$risk_score,col=mypalette2[6],pch=20,cex=0.8)
points(High_NAM$estimated_birth_year,High_NAM$risk_score,col=mypalette2[8],pch=20,cex=0.8)
lines(x = 1932:1993, y = coefficients(Lowest_model_center)[1] + coefficients(Lowest_model_center)[2]* (1932:1993), col =mypalette2[3],lwd = 3)
lines(x = 1932:1993, y = coefficients(Lower_model_center)[1] + coefficients(Lower_model_center)[2]* (1932:1993), col =mypalette2[5],lwd = 3)
lines(x = 1932:1993, y = coefficients(Moderate_model_center)[1] + coefficients(Moderate_model_center)[2]* (1932:1993), col =mypalette2[6],lwd = 3)
lines(x = 1932:1993, y = coefficients(High_model_center)[1] + coefficients(High_model_center)[2]* (1932:1993), col =mypalette2[8],lwd = 3)
lines(x = 1932:1993, y = coefficients(all_groups_center)[1] + coefficients(all_groups_center)[2]* (1932:1993), col = 'black',lwd = 3)
legend("topright", legend=c("0.01<AI<0.37","0.37<AI<0.46","0.46<AI<0.58","0.58<AI","All"),
       col=c(mypalette2[3],mypalette2[5],mypalette2[6],mypalette2[8],"black"), bg="white",lty=1, lwd=2,cex=0.4)
dev.off()


```

```{r}
summary(all_groups_center)
```