---
title: "global_ancestry_analyses_supps"
author: "Melissa Spear"
date: "07/05/2020"
output: html_document
---
The following describes the analyses discussed within the global ancestry analyses of the paper. This includes Supplementary Figures 1-5 and Supplementay Table 1.

The following section is for Supplementary Figure 1 of the paper 

```{r}
NAM_phenotypes<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/ref_panel_related/Reich2012_NAM_refs_only_tribe_country.txt",header=T,sep=" ")

############################################################################
####Plotting the UMAP plot, cleared history and copied/pasted 
fam_filename<-"/Users/melissaspear/Dropbox/HCHS_SOL/smartPCA/data/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.fam"
fam_file<-read.table(fam_filename,header=F,sep=" ")
names(fam_file)<-c("FID","IID","PID","MID","Sex","Pheno")


#Reading in the phenotype 
all_samples_pheno<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_allphenotypes_ALL_samples_new_birthyear.txt", header=T, sep ='\t')
pheno_shortened<-subset(all_samples_pheno, select = c("SUBJECT_ID", "estimated_birth_year", "BKGRD1_C7"))
combined_pheno_fam<-merge(pheno_shortened, fam_file, by.x=c("SUBJECT_ID"), by.y =c("FID"))

#merging the umap results with the HCHS/SOL phenotypes 

latinx_color_palette<-(brewer.pal(7,"Set2"))
latinx_color_palette2<-(brewer.pal(11,"BrBG"))

umap_results_filename<-"/Users/melissaspear/Dropbox/HCHS_SOL/UMAP/overlap_with_ref/projections/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED_UMAP_PC3_NC2_NN15_MD0.5_201944194827.txt"
umap_results  <- read.table(umap_results_filename,header=F)
final_umap_file<-cbind(fam_file,umap_results)

CEU<-final_umap_file[1:104,]
CEU$Population = "CEU" 

YRI<-final_umap_file[105:211,]
YRI$Population = "YRI"

NAM<-final_umap_file[212:323,]
NAM$Population = "NAM"
NAM_umap_with_pheno<-merge(NAM_phenotypes,NAM,by.x=c("IID"),by.y=c("IID"))
Final_NAM_pops<-subset(NAM_umap_with_pheno,select=c("IID","Country","V1","V2")) #Grouping the Populations by Country

CEU_pop = subset(CEU,select=c("IID","Population","V1","V2"))
YRI_pop = subset(YRI,select=c("IID","Population","V1","V2"))

names(Final_NAM_pops)<-c("IID","Population","V1","V2")
umap_pheno<-merge(combined_pheno_fam, final_umap_file, by.x=c("SUBJECT_ID"), by.y =c("FID"))
umap_pheno_subset<-subset(umap_pheno, select=c("IID.x","estimated_birth_year","BKGRD1_C7","V1","V2"))
  
#subset the latinx groups 
Dominican_reclassified<-umap_pheno_subset[which(umap_pheno_subset$BKGRD1_C7 == "0"),]
Central_American_reclassified<-umap_pheno_subset[which(umap_pheno_subset$BKGRD1_C7 == "1"),]
Cuban_reclassified<-umap_pheno_subset[which(umap_pheno_subset$BKGRD1_C7 == "2"),]
Mexican_reclassified<-umap_pheno_subset[which(umap_pheno_subset$BKGRD1_C7 == "3"),]
Puerto_Rican_reclassified<-umap_pheno_subset[which(umap_pheno_subset$BKGRD1_C7 == "4"),]
South_American_reclassified<-umap_pheno_subset[which(umap_pheno_subset$BKGRD1_C7 == "5"),]
Mixed_Other<-umap_pheno_subset[which(umap_pheno_subset$BKGRD1_C7 == "6"),]
  
Cuban_reclassified$Population = "HCHS/SOL-Cuban"
Dominican_reclassified$Population = "HCHS/SOL-Dominican"
Puerto_Rican_reclassified$Population = "HCHS/SOL-Puerto Rican"
Mexican_reclassified$Population = "HCHS/SOL-Mexican"
Central_American_reclassified$Population = "HCHS/SOL-Central American"
South_American_reclassified$Population = "HCHS/SOL-South American"
Mixed_Other$Population = "HCHS/SOL-Mixed/Other"
  
all_Latinx_pops<-rbind(Mexican_reclassified,Puerto_Rican_reclassified,Cuban_reclassified,Dominican_reclassified,Central_American_reclassified,South_American_reclassified,Mixed_Other)
Final_Latinx_pops<-subset(all_Latinx_pops,select=c("IID.x","Population","V1","V2"))
names(Final_Latinx_pops)<-c("IID","Population","V1","V2")
  
all_pops<-rbind(Final_Latinx_pops,Final_NAM_pops,CEU_pop,YRI_pop)

####separating out teh nam pops 

Mexico = Final_NAM_pops[which(Final_NAM_pops$Population=="Mexico"),]
Guatemala = Final_NAM_pops[which(Final_NAM_pops$Population=="Guatemala"),]
Costa_Rica = Final_NAM_pops[which(Final_NAM_pops$Population=="Costa_Rica"),]
Colombia = Final_NAM_pops[which(Final_NAM_pops$Population=="Colombia"),]
Guiana = Final_NAM_pops[which(Final_NAM_pops$Population=="Guiana"),]
Brazil = Final_NAM_pops[which(Final_NAM_pops$Population=="Brazil"),]
Bolivia_Peru = Final_NAM_pops[which(Final_NAM_pops$Population=="Bolivia_Peru"),]
Bolivia_Chile = Final_NAM_pops[which(Final_NAM_pops$Population=="Bolivia_Chile"),]
Paraguay_Argentina = Final_NAM_pops[which(Final_NAM_pops$Population=="Paraguay_Argentina"),]
Argentina = Final_NAM_pops[which(Final_NAM_pops$Population=="Argentina"),]
Chile = Final_NAM_pops[which(Final_NAM_pops$Population=="Chile"),]

### Colors by Country 
require(RColorBrewer)
mypalette<-(brewer.pal(11,"RdYlBu"))

#grey scale- supplementary figure 1C  
paired<-(brewer.pal(12,"Paired"))
set3<-(brewer.pal(9,"Set3"))


#pdf('/Users/melissaspear/Dropbox/HCHS_SOL/UMAP/overlap_with_ref/plots/HCHS_SOL_with_ref_mixed_other_101619_3PCs_greycolors_NAMhighlighted_topleft_legend.pdf',height=2.375,width=2.375,pointsize=5)
par(mar=c(2.1,2.1,0.1,0.1))  
#par(mar=c(3,3,1,1))
#legend("bottomright",legend=c("HCHS/SOL-Cuban","HCHS/SOL-Dominican","HCHS/SOL-Puerto Rican","HCHS/SOL-Mexican","HCHS/SOL-Central American","HCHS/SOL-South American","HCHS/SOL-Mixed/Other"),col=c("#543005","#DFC27D","#8C510A","#003C30", "#01665E","#80CDC1","#F5F5F5"),pch=5,cex=0.6,bg='white')
plot(all_pops$V1,all_pops$V2,pch=0,type='n',xlab="",ylab="",xaxt='n',yaxt='n',bty='n')
legend("topleft",legend=c("Mexico","Guatemala","Costa_Rica","Colombia","Guiana","Brazil","Bolivia/Peru","Bolivia/Chile","Paraguay/Argentina","Argentina","Chile","CEU","YRI"),col=c(paired[2],paired[5],paired[1],paired[4],paired[3],paired[6],paired[7],paired[8],paired[9],paired[10],paired[11],"black","darkgrey"),pch=18,cex=0.65,bg='white',bty = "n")

points(Mexican_reclassified$V1,Mexican_reclassified$V2,col=set3[9],pch=5,cex=0.1)
points(Central_American_reclassified$V1,Central_American_reclassified$V2,col=set3[9],pch=5,cex=0.1)
points(South_American_reclassified$V1,South_American_reclassified$V2,col=set3[9],pch=5,cex=0.1)
points(Dominican_reclassified$V1,Dominican_reclassified$V2,col=set3[9],pch=5,cex=0.1)
points(Cuban_reclassified$V1,Cuban_reclassified$V2,col=set3[9],pch=5,cex=0.1)
points(Puerto_Rican_reclassified$V1,Puerto_Rican_reclassified$V2,col=set3[9],pch=5,cex=0.1)
points(Mixed_Other$V1,Mixed_Other$V2,col=set3[9],pch=5,cex=0.1)
points(CEU$V1,CEU$V2,col="black",pch=18,cex=0.6)
points(YRI$V1,YRI$V2,col="darkgrey",pch=18,cex=0.6)
#points(NAM$V1,NAM$V2,col=pcol2[1],pch=5,cex=0.1)
points(Mexico$V1,Mexico$V2,col=paired[2],pch=18,cex=0.6)
points(Guatemala$V1,Guatemala$V2,col=paired[5],pch=18,cex=0.6)
points(Costa_Rica$V1,Costa_Rica$V2,col=paired[1],pch=18,cex=0.6)
points(Colombia$V1,Colombia$V2,col=paired[4],pch=18,cex=0.6)
points(Guiana$V1,Guiana$V2,col=paired[3],pch=18,cex=0.6)
points(Brazil$V1,Brazil$V2,col=paired[6],pch=18,cex=0.6)
points(Bolivia_Peru$V1,Bolivia_Peru$V2,col=paired[7],pch=18,cex=0.6)
points(Bolivia_Chile$V1,Bolivia_Chile$V2,col=paired[8],pch=18,cex=0.6)
points(Paraguay_Argentina$V1,Paraguay_Argentina$V2,col=paired[9],pch=18,cex=0.6)
points(Argentina$V1,Argentina$V2,col=paired[10],pch=18,cex=0.6)
points(Chile$V1,Chile$V2,col=paired[11],pch=18,cex=0.6)

#dev.off()

```

```{r}
#Supplementary Figure 2
allchr = read.table("/Volumes/LaCie/Downloads/HCHS_SOL_only_ALLChr_RFMix_global_ancestry_estimates_050819.txt", header=T, stringsAsFactor = F)

# Reading in the ADMIXTURE estimates
HCHS_SOL_admixture_file<-read.table("/Volumes/LaCie/Downloads/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.3.Q",header=F,sep=' ')
names(HCHS_SOL_admixture_file)<-c("YRI","CEU","NAM")

#reading in the fam file accompaniment of the .bed file i used for the admixture run 
fam_file = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.fam", header=F, sep = ' ')
fam_file_with_IDs <- cbind(fam_file, HCHS_SOL_admixture_file)

#Merge admixture estiamtes with RFMix estimates
admixture_with_RFMIX_global <- merge(fam_file_with_IDs, allchr, by.x =c("V2"), by.y=c("SAMPLE_ID"))

```

Supplementary Figure 2
```{r}
#####Plotting the plot for the paper. 
require(RColorBrewer)
pcol=brewer.pal(9, "Set1")

#Euro = Red, Native=Blue,African =Green
#pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper/figures/HCHS_SOL_RFMix_ADMIXTURE_ancestry_concordance_050819.pdf",height=2.25,width=7.25,pointsize=10)
par(mfrow=c(1,3))
par(mar=c(2.1,2.1,0.1,0.1))
plot(1,1,type='n',xlim=c(0,1),ylim=c(0,1),xlab="",ylab="",xaxt='n',yaxt='n')
abline(h=seq(0,1,by=0.1),col=rgb(0,0,0,0.1))
abline(v=seq(0,1,by=0.1),col=rgb(0,0,0,0.1))
abline(0,1,col="black")
axis(side=1,padj=-2,cex.axis=0.7)
axis(side=2,padj=1.5,cex.axis=0.7)
mtext(side=1,"ADMIXTURE (%)",line=1.1,cex=0.75)
mtext(side=2,"RFMix (%)",line=1.1,cex=0.75)
points(admixture_with_RFMIX_global$NAM.x, admixture_with_RFMIX_global$NAM_global_mean,col=pcol[2],pch=16,cex=.5)
plot(1,1,type='n',xlim=c(0,1),ylim=c(0,1),xlab="",ylab="",xaxt='n',yaxt='n')
abline(h=seq(0,1,by=0.1),col=rgb(0,0,0,0.1))
abline(v=seq(0,1,by=0.1),col=rgb(0,0,0,0.1))
abline(0,1,col="black")
axis(side=1,padj=-2,cex.axis=0.7)
axis(side=2,padj=1.5,cex.axis=0.7)
mtext(side=1,"ADMIXTURE (%)",line=1.1,cex=0.75)
mtext(side=2,"RFMix (%)",line=1.1,cex=0.75)
points(admixture_with_RFMIX_global$YRI, admixture_with_RFMIX_global$AFR_global_mean,col=pcol[1],pch=16,cex=.5)
plot(1,1,type='n',xlim=c(0,1),ylim=c(0,1),xlab="",ylab="",xaxt='n',yaxt='n')
abline(h=seq(0,1,by=0.1),col=rgb(0,0,0,0.1))
abline(v=seq(0,1,by=0.1),col=rgb(0,0,0,0.1))
abline(0,1,col="black")
axis(side=1,padj=-2,cex.axis=0.7)
axis(side=2,padj=1.5,cex.axis=0.7)
mtext(side=1,"ADMIXTURE (%)",line=1.1,cex=0.75)
mtext(side=2,"RFMix (%)",line=1.1,cex=0.75)
points(admixture_with_RFMIX_global$CEU, admixture_with_RFMIX_global$EUR_global_mean,col=pcol[3],pch=16,cex=.5)
#dev.off()

```

Supplementary Figure 3
```{r}
allchr = read.table("/Volumes/LaCie/Downloads/HCHS_SOL_only_ALLChr_RFMix_global_ancestry_estimates_050819.txt", header=T, stringsAsFactor = F)

# Reading in the ADMIXTURE estimates
HCHS_SOL_admixture_file<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.3.Q",header=F,sep=' ')
names(HCHS_SOL_admixture_file)<-c("YRI","CEU","NAM")

#reading in the fam file accompaniment of the .bed file i used for the admixture run 
fam_file = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.fam", header=F, sep = ' ')
fam_file_with_IDs <- cbind(fam_file, HCHS_SOL_admixture_file)

#Merge admixture estiamtes with RFMix estimates
d = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T,sep='\t')

admixture_with_RFMIX_global <- merge(fam_file_with_IDs, allchr, by.x =c("V2"), by.y=c("SAMPLE_ID"))

pheno_new_global_ancestry_estiamtes<-merge(d,admixture_with_RFMIX_global,by.x=c("V2"),by.y=c("V2"))

fit = lm(pheno_new_global_ancestry_estiamtes[,301] ~ pheno_new_global_ancestry_estiamtes[,284]+log(pheno_new_global_ancestry_estiamtes[,179])) #linear model: Native ancestry vs birth year

fit = lm(pheno_new_global_ancestry_estiamtes[,301] ~ pheno_new_global_ancestry_estiamtes[,284]+log(pheno_new_global_ancestry_estiamtes[,179])) #linear model: Native ancestry vs birth year


#plot code it self 
#pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper/figures/HCHS_SOL_RFMix_NativeAmerican_ancestry_points+wiskers_dbins_071519_supplementary_figure3.pdf",height=2.25,width=2.375,pointsize=10)
par(mar=c(2.1,2.1,0.1,0.1))
plot(1,1,type='n',xlim=range(pheno_new_global_ancestry_estiamtes[,284]),ylim=c(0,1),xlab="",ylab="",xaxt='n',yaxt='n')
abline(h=seq(0,1,by=0.1),col=rgb(0,0,0,0.1))
abline(v=seq(1930,2000,by=5),col=rgb(0,0,0,0.1))
axis(side=1,padj=-2,cex.axis=0.7)
axis(side=2,padj=1.5,cex.axis=0.7)
mtext(side=1,"Birth year",line=1.1)
mtext(side=2,"Amerindigenous ancestry (%)",line=1.1)
c=col2rgb(pcol[2])/255;
I1 = which.min(pheno_new_global_ancestry_estiamtes[,284])
I2 = which.max(pheno_new_global_ancestry_estiamtes[,284])
points(pheno_new_global_ancestry_estiamtes[,284],pheno_new_global_ancestry_estiamtes[,301],col=rgb(c[1],c[2],c[3],0.2),pch=16,cex=0.5)
segments(x0=pheno_new_global_ancestry_estiamtes[I1,284], x1=pheno_new_global_ancestry_estiamtes[I2,284],y0=fit$fitted.values[I1],y1=fit$fitted.values[I2],col="white",lwd=3)
segments(x0=pheno_new_global_ancestry_estiamtes[I1,284], x1=pheno_new_global_ancestry_estiamtes[I2,284],y0=fit$fitted.values[I1],y1=fit$fitted.values[I2],col=pcol[2],lwd=2)

pw = 10 #partition width, in years
part=seq(min(floor(pheno_new_global_ancestry_estiamtes[,301]/10)*10),max(ceiling(pheno_new_global_ancestry_estiamtes[,284]/10)*10),by=pw)
for(i in 1:(length(part)-1)){
  q1 = max(part[i],min(pheno_new_global_ancestry_estiamtes[,284]));
  q2 = min(part[i+1],max(pheno_new_global_ancestry_estiamtes[,284]));
  dbin = pheno_new_global_ancestry_estiamtes[which(pheno_new_global_ancestry_estiamtes[,284]>q1 & pheno_new_global_ancestry_estiamtes[,284]<=q2),]
  m = mean(dbin[,301],na.rm=T)
  se = 2*sd(dbin[,301],na.rm=T)/sqrt(nrow(dbin))
  segments(x0=q1,x1=q2,y0=m)
  segments(x0=(q1+q2)/2,y0=m-se,y1=m+se)
  cat(i,q1,q2,m,se,"\n",sep="\t")
}
#dev.off()

```

Supplementary Figure 4 
```{r}
setwd("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures")
MX_pheno<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T,sep='\t')

no_na=MX_pheno[which(!is.na(MX_pheno$CLINDATE_YR)),]
with_na = MX_pheno[which(is.na(MX_pheno$CLINDATE_YR)),]
fit = lm(NAM ~ estimated_birth_year+WEIGHT_FINAL_NORM_OVERALL,data=no_na)

library(boot)

MX_1930s<-MX_pheno[which(MX_pheno$estimated_birth_year>='1930'&MX_pheno$estimated_birth_year<'1940'),]
MX_1930s$Decade<-"1930s"

MX_1940s<-MX_pheno[which(MX_pheno$estimated_birth_year>='1940'&MX_pheno$estimated_birth_year<'1950'),]
MX_1940s$Decade<-"1940s"

MX_1950s<-MX_pheno[which(MX_pheno$estimated_birth_year>='1950'&MX_pheno$estimated_birth_year<'1960'),]
MX_1950s$Decade<-"1950s"

MX_1960s<-MX_pheno[which(MX_pheno$estimated_birth_year>='1960'&MX_pheno$estimated_birth_year<'1970'),]
MX_1960s$Decade<-"1960s"

MX_1970s<-MX_pheno[which(MX_pheno$estimated_birth_year>='1970'&MX_pheno$estimated_birth_year<'1980'),]
MX_1970s$Decade<-"1970s"

MX_1980s<-MX_pheno[which(MX_pheno$estimated_birth_year>='1980'&MX_pheno$estimated_birth_year<'1990'),]
MX_1980s$Decade<-"1980s"

MX_1990s<-MX_pheno[which(MX_pheno$estimated_birth_year>='1990'),]
MX_1990s$Decade<-"1990s"


#9 is the 9th column which is the NAM column 
sapply(9, function(x) mean(MX_1930s[,x]))
sapply(9, function(x) mean(MX_1940s[,x]))
sapply(9, function(x) mean(MX_1950s[,x]))
sapply(9, function(x) mean(MX_1960s[,x]))
sapply(9, function(x) mean(MX_1970s[,x]))
sapply(9, function(x) mean(MX_1980s[,x]))
sapply(9, function(x) mean(MX_1990s[,x]))


#Bootstrap resampling

#1930s
set.seed(1234)
resamples_1930s<-lapply(1:1000,function(i) sample(MX_1930s$NAM,replace=T))
resamples_means_1930s<-sapply(resamples_1930s,mean)
#sqrt(var(resamples_means_1930s))


#1940s
set.seed(1234)
resamples_1940s<-lapply(1:1000,function(i) sample(MX_1940s$NAM,replace=T))
resamples_means_1940s<-sapply(resamples_1940s,mean)
#sqrt(var(resamples_means_1940s))

#1950s
set.seed(1234)
resamples_1950s<-lapply(1:1000,function(i) sample(MX_1950s$NAM,replace=T))
resamples_means_1950s<-sapply(resamples_1950s,mean)
#sqrt(var(resamples_means_1950s))

#1960s
set.seed(1234)
resamples_1960s<-lapply(1:1000,function(i) sample(MX_1960s$NAM,replace=T))
resamples_means_1960s<-sapply(resamples_1960s,mean)
#sqrt(var(resamples_means_1960s))

#1970s
set.seed(1234)
resamples_1970s<-lapply(1:1000,function(i) sample(MX_1970s$NAM,replace=T))
resamples_means_1970s<-sapply(resamples_1970s,mean)
#sqrt(var(resamples_means_1970s))

#1980s
set.seed(1234)
resamples_1980s<-lapply(1:1000,function(i) sample(MX_1980s$NAM,replace=T))
resamples_means_1980s<-sapply(resamples_1980s,mean)
#sqrt(var(resamples_means_1980s))

#1990s
set.seed(1234)
resamples_1990s<-lapply(1:1000,function(i) sample(MX_1990s$NAM,replace=T))
resamples_means_1990s<-sapply(resamples_1990s,mean)
#sqrt(var(resamples_means_1990s))

########################
#
# Plotting the ridgeline plot of the bootstrap resampling 
#
########################
library(ggplot2)
library(ggridges)
#need to reshape the data

#reshaping the data in order to work with ggridges
#1930s
df.means.1930s=data.frame(resamples_means_1930s)
names(df.means.1930s)=c("NAM_means")
df.means.1930s$Decade<-"1930s"
df.means.1930s$ascending_decade<-"1"
df.means.1930s$descending_decade<-"7"

#1940s
df.means.1940s=data.frame(resamples_means_1940s)
names(df.means.1940s)=c("NAM_means")
df.means.1940s$Decade<-"1940s"
df.means.1940s$ascending_decade<-"2"
df.means.1940s$descending_decade<-"6"

#1950s
df.means.1950s=data.frame(resamples_means_1950s)
names(df.means.1950s)=c("NAM_means")
df.means.1950s$Decade<-"1950s"
df.means.1950s$ascending_decade<-"3"
df.means.1950s$descending_decade<-"5"

#1960s
df.means.1960s=data.frame(resamples_means_1960s)
names(df.means.1960s)=c("NAM_means")
df.means.1960s$Decade<-"1960s"
df.means.1960s$ascending_decade<-"4"
df.means.1960s$descending_decade<-"4"

#1970s
df.means.1970s=data.frame(resamples_means_1970s)
names(df.means.1970s)=c("NAM_means")
df.means.1970s$Decade<-"1970s"
df.means.1970s$ascending_decade<-"5"
df.means.1970s$descending_decade<-"3"

#1980s
df.means.1980s=data.frame(resamples_means_1980s)
names(df.means.1980s)=c("NAM_means")
df.means.1980s$Decade<-"1980s"
df.means.1980s$ascending_decade<-"6"
df.means.1980s$descending_decade<-"2"

#1990s
df.means.1990s=data.frame(resamples_means_1990s)
names(df.means.1990s)=c("NAM_means")
df.means.1990s$Decade<-"1990s"
df.means.1990s$ascending_decade<-"7"
df.means.1990s$descending_decade<-"1"


all_decades<-rbind(df.means.1930s,df.means.1940s,df.means.1950s,df.means.1960s,df.means.1970s,df.means.1980s,df.means.1990s)

require(RColorBrewer)
myColors=brewer.pal(7, "Set1")

#Plotting ridgeline plot
pdf("MX_NAM_ancestry_ridgeline_plot_bootstrap_resampling_072319_supplementary_figure4.pdf",height=2.375,width=2.375,pointsize=10)
par(mar=c(2.1,2.1,0.1,0.2))
ggplot(all_decades,aes(x=NAM_means,y=Decade,fill=factor(Decade))) +
  geom_density_ridges(scale=1)+ theme_bw() + theme(axis.text.x=element_text(size=rel(0.8)),axis.text.y=element_text(size=rel(0.8))) + theme(axis.title.x = element_text(size=10),axis.title.y = element_text(size=10))+
  scale_y_discrete(expand=c(0.1,0)) + scale_fill_manual(values=c("#E41A1C","#FF7F00","#FFFF33","#4DAF4A","#377EB8","#984EA3","#A65628")) + theme(legend.position = "none") + labs(x="Amerindigenous ancestry (%)", y="Decades")
dev.off()

```

Supplementary Figure 5  code is at https://github.com/diazale/hispanic_admix/blob/master/code/hrs_admix.R
