---
title: "local_ancestry_analyses_fig2"
author: "Melissa Spear"
date: "13/05/2020"
output: html_document
---

Figure 2A
```{r}
setwd("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures")
fst=read.table("/Volumes/LaCie/Downloads/results/HCHS_SOL_Mexicans_PI_all_decades_gen_back_061719.txt",header=T,sep='\t')
names(fst)=c("IID1","IID2","pi","gen_back","order_cat","Decade_initial")


#Reading in the pheno file to separate by migrant status 
d = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T,sep='\t')
pheno_subsetted<-subset(d,select=c("V1","V2","US_BORN","estimated_birth_year"))

first_match<-merge(fst,pheno_subsetted,by.x=c("IID1"),by.y=c("V2"))
names(first_match)=c("IID1","IID2","pi","gen_back","order_cat","Decade_initial","V1_IID1","US_born_IID1","estimated_birth_year1")

second_match<-merge(first_match,pheno_subsetted,by.x=c("IID2"),by.y=c("V2"))
names(second_match)=c("IID2","IID1","pi","gen_back","order_cat","Decade_initial","V1_IID1","US_born_IID1","estimated_birth_year1","V1_IID2","US_born_IID2","estimated_birth_year2")

```

```{r}
#subsetting of datasets 
require(RColorBrewer)
myColors=brewer.pal(7, "Set1")


samples_30s_US_born<-pheno_subsetted[which(pheno_subsetted$US_BORN=="1" & pheno_subsetted$estimated_birth_year<1940),]
#90s
all_90s_pi = fst[which(fst$Decade_initial=="1990s"),]
means_90s = aggregate(all_90s_pi[,3], list(all_90s_pi$gen_back), mean)
means_90s_dataframe = c(means_90s$x)

all_90s_pi_0 = fst[which(fst$Decade_initial=="1990s" & fst$gen_back=="0"),]
mean_90s_0<-mean(all_90s_pi_0$pi)

all_90s_pi_1 = fst[which(fst$Decade_initial=="1990s" & fst$gen_back=="1"),]
mean_90s_1<-mean(all_90s_pi_1$pi)

all_90s_pi_2 = fst[which(fst$Decade_initial=="1990s" & fst$gen_back=="2"),]
mean_90s_2<-mean(all_90s_pi_2$pi)

all_90s_pi_3 = fst[which(fst$Decade_initial=="1990s" & fst$gen_back=="3"),]
mean_90s_3<-mean(all_90s_pi_3$pi)

all_90s_pi_4 = fst[which(fst$Decade_initial=="1990s" & fst$gen_back=="4"),]
mean_90s_4<-mean(all_90s_pi_4$pi)

all_90s_pi_5 = fst[which(fst$Decade_initial=="1990s" & fst$gen_back=="5"),]
mean_90s_5<-mean(all_90s_pi_5$pi)

all_90s_pi_6 = fst[which(fst$Decade_initial=="1990s" & fst$gen_back=="6"),]
mean_90s_6<-mean(all_90s_pi_6$pi)


#80s
all_80s_pi = fst[which(fst$Decade_initial=="1980s"),]
means_80s = aggregate(all_80s_pi[,3], list(all_80s_pi$gen_back), mean)
means_80s_dataframe = c(means_80s$x)

all_80s_pi_0 = fst[which(fst$Decade_initial=="1980s" & fst$gen_back=="0"),]
mean_80s_0<-mean(all_80s_pi_0$pi)

all_80s_pi_1 = fst[which(fst$Decade_initial=="1980s" & fst$gen_back=="1"),]
mean_80s_1<-mean(all_80s_pi_1$pi)

all_80s_pi_2 = fst[which(fst$Decade_initial=="1980s" & fst$gen_back=="2"),]
mean_80s_2<-mean(all_80s_pi_2$pi)

all_80s_pi_3 = fst[which(fst$Decade_initial=="1980s" & fst$gen_back=="3"),]
mean_80s_3<-mean(all_80s_pi_3$pi)

all_80s_pi_4 = fst[which(fst$Decade_initial=="1980s" & fst$gen_back=="4"),]
mean_80s_4<-mean(all_80s_pi_4$pi)

all_80s_pi_5 = fst[which(fst$Decade_initial=="1980s" & fst$gen_back=="5"),]
mean_80s_5<-mean(all_80s_pi_5$pi)

#70s
all_70s_pi = fst[which(fst$Decade_initial=="1970s"),]
means_70s = aggregate(all_70s_pi[,3], list(all_70s_pi$gen_back), mean)
means_70s_dataframe = c(means_70s$x)

all_70s_pi_0 = fst[which(fst$Decade_initial=="1970s" & fst$gen_back=="0"),]
mean_70s_0<-mean(all_70s_pi_0$pi)

all_70s_pi_1 = fst[which(fst$Decade_initial=="1970s" & fst$gen_back=="1"),]
mean_70s_1<-mean(all_70s_pi_1$pi)

all_70s_pi_2 = fst[which(fst$Decade_initial=="1970s" & fst$gen_back=="2"),]
mean_70s_2<-mean(all_70s_pi_2$pi)

all_70s_pi_3 = fst[which(fst$Decade_initial=="1970s" & fst$gen_back=="3"),]
mean_70s_3<-mean(all_70s_pi_3$pi)

all_70s_pi_4 = fst[which(fst$Decade_initial=="1970s" & fst$gen_back=="4"),]
mean_70s_4<-mean(all_70s_pi_4$pi)

#60s
all_60s_pi = fst[which(fst$Decade_initial=="1960s"),]
means_60s = aggregate(all_60s_pi[,3], list(all_60s_pi$gen_back), mean)
means_60s_dataframe = c(means_60s$x)

all_60s_pi_0 = fst[which(fst$Decade_initial=="1960s" & fst$gen_back=="0"),]
mean_60s_0<-mean(all_60s_pi_0$pi)

all_60s_pi_1 = fst[which(fst$Decade_initial=="1960s" & fst$gen_back=="1"),]
mean_60s_1<-mean(all_60s_pi_1$pi)

all_60s_pi_2 = fst[which(fst$Decade_initial=="1960s" & fst$gen_back=="2"),]
mean_60s_2<-mean(all_60s_pi_2$pi)

all_60s_pi_3 = fst[which(fst$Decade_initial=="1960s" & fst$gen_back=="3"),]
mean_60s_3<-mean(all_60s_pi_3$pi)

#50s
all_50s_pi = fst[which(fst$Decade_initial=="1950s"),]
means_50s = aggregate(all_50s_pi[,3], list(all_50s_pi$gen_back), mean)
means_50s_dataframe = c(means_50s$x)

all_50s_pi_0 = fst[which(fst$Decade_initial=="1950s" & fst$gen_back=="0"),]
mean_50s_0<-mean(all_50s_pi_0$pi)

all_50s_pi_1 = fst[which(fst$Decade_initial=="1950s" & fst$gen_back=="1"),]
mean_50s_1<-mean(all_50s_pi_1$pi)

all_50s_pi_2 = fst[which(fst$Decade_initial=="1950s" & fst$gen_back=="2"),]
mean_50s_2<-mean(all_50s_pi_2$pi)

#40s
all_40s_pi = fst[which(fst$Decade_initial=="1940s"),]
means_40s = aggregate(all_40s_pi[,3], list(all_40s_pi$gen_back), mean)
means_40s_dataframe = c(means_40s$x)

all_40s_pi_0 = fst[which(fst$Decade_initial=="1940s" & fst$gen_back=="0"),]
mean_40s_0<-mean(all_40s_pi_0$pi)

all_40s_pi_1 = fst[which(fst$Decade_initial=="1940s" & fst$gen_back=="1"),]
mean_40s_1<-mean(all_40s_pi_1$pi)

#30s
all_30s_pi = fst[which(fst$Decade_initial=="1930s"),]
means_30s = aggregate(all_30s_pi[,3], list(all_30s_pi$gen_back), mean)
means_30s_dataframe = c(means_30s$x)

all_30s_pi_0 = fst[which(fst$Decade_initial=="1930s" & fst$gen_back=="0"),]
mean_30s_0<-mean(all_30s_pi_0$pi)

```

```{r}
###################################################
# Bootstrap resampling of Pi to get the 95% confidence interval 
###################################################
#because of the large dataset, stored outputs to variables and and reran

#30s 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(all_30s_pi_0$pi,replace=T)
    #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_30_0_bound<-quantile(bstrap,.025)
upper_30_0_bound<-quantile(bstrap,.975)

#40s 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(all_40s_pi_0$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_40_0_bound<-quantile(bstrap,.025)
upper_40_0_bound<-quantile(bstrap,.975)

#50s 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(all_50s_pi_0$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_50_0_bound<-quantile(bstrap,.025)
upper_50_0_bound<-quantile(bstrap,.975)

#60s 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(all_60s_pi_0$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_60_0_bound<-quantile(bstrap,.025)
upper_60_0_bound<-quantile(bstrap,.975)

#70s 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(all_70s_pi_0$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_70_0_bound<-quantile(bstrap,.025)
upper_70_0_bound<-quantile(bstrap,.975)

#80s 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(all_80s_pi_0$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_80_0_bound<-quantile(bstrap,.025)
upper_80_0_bound<-quantile(bstrap,.975)

#90s
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(all_90s_pi_0$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_90_0_bound<-quantile(bstrap,.025)
upper_90_0_bound<-quantile(bstrap,.975)

```

```{r}
#subsetting of indivudals 
#############################
#Us born vs us migrant

##US born compared to us migrant 

us_born_migrant = second_match[which((second_match$US_born_IID1=="0" & second_match$US_born_IID2=="1") | (second_match$US_born_IID1=="1" & second_match$US_born_IID2=="0")),]

all_90s_pi_us_born_migrant = us_born_migrant[which(us_born_migrant$Decade_initial=="1990s"),]
all_80s_pi_us_born_migrant = us_born_migrant[which(us_born_migrant$Decade_initial=="1980s"),]
all_70s_pi_us_born_migrant = us_born_migrant[which(us_born_migrant$Decade_initial=="1970s"),]
all_60s_pi_us_born_migrant = us_born_migrant[which(us_born_migrant$Decade_initial=="1960s"),]
all_50s_pi_us_born_migrant = us_born_migrant[which(us_born_migrant$Decade_initial=="1950s"),]
all_40s_pi_us_born_migrant = us_born_migrant[which(us_born_migrant$Decade_initial=="1940s"),]
all_30s_pi_us_born_migrant = us_born_migrant[which(us_born_migrant$Decade_initial=="1930s"),]

#####extracting only the starting gens 
us_born_migrant_90s_90s=all_90s_pi_us_born_migrant[which(all_90s_pi_us_born_migrant$gen_back=='0'),]
us_born_migrant_80s_80s=all_80s_pi_us_born_migrant[which(all_80s_pi_us_born_migrant$gen_back=='0'),]
us_born_migrant_70s_70s=all_70s_pi_us_born_migrant[which(all_70s_pi_us_born_migrant$gen_back=='0'),]
us_born_migrant_60s_60s=all_60s_pi_us_born_migrant[which(all_60s_pi_us_born_migrant$gen_back=='0'),]
us_born_migrant_50s_50s=all_50s_pi_us_born_migrant[which(all_50s_pi_us_born_migrant$gen_back=='0'),]
us_born_migrant_40s_40s=all_40s_pi_us_born_migrant[which(all_40s_pi_us_born_migrant$gen_back=='0'),]
us_born_migrant_30s_30s=all_30s_pi_us_born_migrant[which(all_30s_pi_us_born_migrant$gen_back=='0'),]

#combine all datasets to find mean
all_us_born_migrant_within_gens<-rbind(us_born_migrant_90s_90s,us_born_migrant_80s_80s,us_born_migrant_70s_70s,us_born_migrant_60s_60s,us_born_migrant_50s_50s,us_born_migrant_40s_40s,us_born_migrant_30s_30s)
means_all_us_born_migrant_within_gens<-aggregate(all_us_born_migrant_within_gens$pi, list(all_us_born_migrant_within_gens$Decade_initial), mean)

```

```{r}
###########
#Running the bootsrap iterations for this group. 

#90s us born-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_migrant_90s_90s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_90_0_bound_us_born_migrant<-quantile(bstrap,.025)
upper_90_0_bound_us_born_migrant<-quantile(bstrap,.975)

#80s us born-migrant
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_migrant_80s_80s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_80_0_bound_us_born_migrant<-quantile(bstrap,.025)
upper_80_0_bound_us_born_migrant<-quantile(bstrap,.975)

#70s us born-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_migrant_70s_70s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_70_0_bound_us_born_migrant<-quantile(bstrap,.025)
upper_70_0_bound_us_born_migrant<-quantile(bstrap,.975)


#60s us born-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_migrant_60s_60s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_60_0_bound_us_born_migrant<-quantile(bstrap,.025)
upper_60_0_bound_us_born_migrant<-quantile(bstrap,.975)

#50s us born-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_migrant_50s_50s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_50_0_bound_us_born_migrant<-quantile(bstrap,.025)
upper_50_0_bound_us_born_migrant<-quantile(bstrap,.975)

#40s us born-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_migrant_40s_40s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_40_0_bound_us_born_migrant<-quantile(bstrap,.025)
upper_40_0_bound_us_born_migrant<-quantile(bstrap,.975)

#30s us born-migrant
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_migrant_30s_30s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_30_0_bound_us_born_migrant<-quantile(bstrap,.025)
upper_30_0_bound_us_born_migrant<-quantile(bstrap,.975)

###merging the CI infroamtion together 
us_born_migrant_dataframe=data.frame(c(1,2,3,4,5,6,7),c(means_all_us_born_migrant_within_gens$x),c(lower_30_0_bound_us_born_migrant[[1]],lower_40_0_bound_us_born_migrant[[1]],lower_50_0_bound_us_born_migrant[[1]],lower_60_0_bound_us_born_migrant[[1]],lower_70_0_bound_us_born_migrant[[1]],lower_80_0_bound_us_born_migrant[[1]],lower_90_0_bound_us_born_migrant[[1]]),c(upper_30_0_bound_us_born_migrant[[1]],upper_40_0_bound_us_born_migrant[[1]],upper_50_0_bound_us_born_migrant[[1]],upper_60_0_bound_us_born_migrant[[1]],upper_70_0_bound_us_born_migrant[[1]],upper_80_0_bound_us_born_migrant[[1]],upper_90_0_bound_us_born_migrant[[1]]))
names(us_born_migrant_dataframe)=c("decade_order","mean","lower_CI","upper_CI")

```


```{r}
#######US born to US born 
us_born_us_born = second_match[which(second_match$US_born_IID1=="1" & second_match$US_born_IID2=="1"),]

us_born_us_born_90s_90s = us_born_us_born[which(us_born_us_born$Decade_initial=="1990s"),]
us_born_us_born_80s_80s = us_born_us_born[which(us_born_us_born$Decade_initial=="1980s"),]
us_born_us_born_70s_70s = us_born_us_born[which(us_born_us_born$Decade_initial=="1970s"),]
us_born_us_born_60s_60s = us_born_us_born[which(us_born_us_born$Decade_initial=="1960s"),]
us_born_us_born_50s_50s = us_born_us_born[which(us_born_us_born$Decade_initial=="1950s"),]
us_born_us_born_40s_40s = us_born_us_born[which(us_born_us_born$Decade_initial=="1940s"),]
us_born_us_born_30s_30s = us_born_us_born[which(us_born_us_born$Decade_initial=="1930s"),]

all_us_born_us_born_within_gens<-rbind(us_born_us_born_90s_90s,us_born_us_born_80s_80s,us_born_us_born_70s_70s,us_born_us_born_60s_60s,us_born_us_born_50s_50s,us_born_us_born_40s_40s,us_born_us_born_30s_30s)
means_all_us_born_us_born_within_gens<-aggregate(all_us_born_us_born_within_gens$pi, list(all_us_born_us_born_within_gens$Decade_initial), mean)


#running the bootstrap iterations 
#90s us born-us_born 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_us_born_90s_90s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_90_0_bound_us_born_us_born<-quantile(bstrap,.025)
upper_90_0_bound_us_born_us_born<-quantile(bstrap,.975)

#80s us born-us_born 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_us_born_80s_80s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_80_0_bound_us_born_us_born<-quantile(bstrap,.025)
upper_80_0_bound_us_born_us_born<-quantile(bstrap,.975)

#70s us born-us_born 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_us_born_70s_70s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_70_0_bound_us_born_us_born<-quantile(bstrap,.025)
upper_70_0_bound_us_born_us_born<-quantile(bstrap,.975)

#60s us born-us_born 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_us_born_60s_60s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_60_0_bound_us_born_us_born<-quantile(bstrap,.025)
upper_60_0_bound_us_born_us_born<-quantile(bstrap,.975)

#50s us born-us_born 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_us_born_50s_50s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_50_0_bound_us_born_us_born<-quantile(bstrap,.025)
upper_50_0_bound_us_born_us_born<-quantile(bstrap,.975)

#40s us born-us_born 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_us_born_40s_40s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_40_0_bound_us_born_us_born<-quantile(bstrap,.025)
upper_40_0_bound_us_born_us_born<-quantile(bstrap,.975)

#30s us born-us_born 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(us_born_us_born_30s_30s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_30_0_bound_us_born_us_born<-quantile(bstrap,.025)
upper_30_0_bound_us_born_us_born<-quantile(bstrap,.975)

###merging the CI infroamtion together 
us_born_us_born_dataframe=data.frame(c(1,2,3,4,5,6,7),c(means_all_us_born_us_born_within_gens$x),c(lower_30_0_bound_us_born_us_born[[1]],lower_40_0_bound_us_born_us_born[[1]],lower_50_0_bound_us_born_us_born[[1]],lower_60_0_bound_us_born_us_born[[1]],lower_70_0_bound_us_born_us_born[[1]],lower_80_0_bound_us_born_us_born[[1]],lower_90_0_bound_us_born_us_born[[1]]),c(upper_30_0_bound_us_born_us_born[[1]],upper_40_0_bound_us_born_us_born[[1]],upper_50_0_bound_us_born_us_born[[1]],upper_60_0_bound_us_born_us_born[[1]],upper_70_0_bound_us_born_us_born[[1]],upper_80_0_bound_us_born_us_born[[1]],upper_90_0_bound_us_born_us_born[[1]]))
names(us_born_us_born_dataframe)=c("decade_order","mean","lower_CI","upper_CI")

```

```{r}
###########
#migrant to migrant

migrant_migrant = second_match[which(second_match$US_born_IID1=="0" & second_match$US_born_IID2=="0"),]

migrant_migrant_90s_90s = migrant_migrant[which(migrant_migrant$Decade_initial=="1990s"),]
migrant_migrant_80s_80s = migrant_migrant[which(migrant_migrant$Decade_initial=="1980s"),]
migrant_migrant_70s_70s = migrant_migrant[which(migrant_migrant$Decade_initial=="1970s"),]
migrant_migrant_60s_60s = migrant_migrant[which(migrant_migrant$Decade_initial=="1960s"),]
migrant_migrant_50s_50s = migrant_migrant[which(migrant_migrant$Decade_initial=="1950s"),]
migrant_migrant_40s_40s = migrant_migrant[which(migrant_migrant$Decade_initial=="1940s"),]
migrant_migrant_30s_30s = migrant_migrant[which(migrant_migrant$Decade_initial=="1930s"),]

all_migrant_migrant_within_gens<-rbind(migrant_migrant_90s_90s,migrant_migrant_80s_80s,migrant_migrant_70s_70s,migrant_migrant_60s_60s,migrant_migrant_50s_50s,migrant_migrant_40s_40s,migrant_migrant_30s_30s)
means_all_migrant_migrant_within_gens<-aggregate(all_migrant_migrant_within_gens$pi, list(all_migrant_migrant_within_gens$Decade_initial), mean)

#running the bootsrap iterations 

#90s migrant-migrant
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(migrant_migrant_90s_90s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_90_0_bound_migrant_migrant<-quantile(bstrap,.025)
upper_90_0_bound_migrant_migrant<-quantile(bstrap,.975)

#80s migrant-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(migrant_migrant_80s_80s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_80_0_bound_migrant_migrant<-quantile(bstrap,.025)
upper_80_0_bound_migrant_migrant<-quantile(bstrap,.975)

#70s migrant-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(migrant_migrant_70s_70s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_70_0_bound_migrant_migrant<-quantile(bstrap,.025)
upper_70_0_bound_migrant_migrant<-quantile(bstrap,.975)

#60s migrant-migrant 
set.seed(1234)
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(migrant_migrant_60s_60s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_60_0_bound_migrant_migrant<-quantile(bstrap,.025)
upper_60_0_bound_migrant_migrant<-quantile(bstrap,.975)

#50s migrant-migrant 
set.seed(1234) 
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(migrant_migrant_50s_50s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_50_0_bound_migrant_migrant<-quantile(bstrap,.025)
upper_50_0_bound_migrant_migrant<-quantile(bstrap,.975)

#40s migrant-migrant 
set.seed(1234) 
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(migrant_migrant_40s_40s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_40_0_bound_migrant_migrant<-quantile(bstrap,.025)
upper_40_0_bound_migrant_migrant<-quantile(bstrap,.975)

#30s migrant-migrant 
set.seed(1234) 
bstrap <- c()
for (i in 1:1000){
  # First take the sample
  bsample <- sample(migrant_migrant_30s_30s$pi,replace=T)
  #now calculate the bootstrap estimate + 
  bestimate <- mean(bsample)
  bstrap <- c(bstrap,bestimate)}

lower_30_0_bound_migrant_migrant<-quantile(bstrap,.025)
upper_30_0_bound_migrant_migrant<-quantile(bstrap,.975)

###combinign all the upper bounds 
migrant_migrant_all_upper_bounds<-rbind(upper_30_0_bound_migrant_migrant[[1]],upper_40_0_bound_migrant_migrant[[1]],upper_50_0_bound_migrant_migrant[[1]],upper_60_0_bound_migrant_migrant[[1]],upper_70_0_bound_migrant_migrant[[1]],upper_80_0_bound_migrant_migrant[[1]],upper_90_0_bound_migrant_migrant[[1]])

migrant_migrant_all_lower_bounds<-rbind(lower_30_0_bound_migrant_migrant[[1]],lower_40_0_bound_migrant_migrant[[1]],lower_50_0_bound_migrant_migrant[[1]],lower_60_0_bound_migrant_migrant[[1]],lower_70_0_bound_migrant_migrant[[1]],lower_80_0_bound_migrant_migrant[[1]],lower_90_0_bound_migrant_migrant[[1]])

###merging the means with the upper and lower bounds 

migrant_migrant_dataframe=data.frame(c(1,2,3,4,5,6,7),c(means_all_migrant_migrant_within_gens$x),c(lower_30_0_bound_migrant_migrant[[1]],lower_40_0_bound_migrant_migrant[[1]],lower_50_0_bound_migrant_migrant[[1]],lower_60_0_bound_migrant_migrant[[1]],lower_70_0_bound_migrant_migrant[[1]],lower_80_0_bound_migrant_migrant[[1]],lower_90_0_bound_migrant_migrant[[1]]),c(upper_30_0_bound_migrant_migrant[[1]],upper_40_0_bound_migrant_migrant[[1]],upper_50_0_bound_migrant_migrant[[1]],upper_60_0_bound_migrant_migrant[[1]],upper_70_0_bound_migrant_migrant[[1]],upper_80_0_bound_migrant_migrant[[1]],upper_90_0_bound_migrant_migrant[[1]]))
names(migrant_migrant_dataframe)=c("decade_order","mean","lower_CI","upper_CI")
```

```{r}
###merging all samples 
all_samples_within_gens=rbind(all_90s_pi_0,all_80s_pi_0,all_70s_pi_0,all_60s_pi_0,all_50s_pi_0,all_40s_pi_0,all_30s_pi_0)
means_all_samples_within_gens<-aggregate(all_samples_within_gens$pi, list(all_samples_within_gens$Decade_initial), mean)


all_samples_dataframe=data.frame(c(1,2,3,4,5,6,7),c(means_all_samples_within_gens$x),c(lower_30_0_bound[[1]],lower_40_0_bound[[1]],lower_50_0_bound[[1]],lower_60_0_bound[[1]],lower_70_0_bound[[1]],lower_80_0_bound[[1]],lower_90_0_bound[[1]]),c(upper_30_0_bound[[1]],upper_40_0_bound[[1]],upper_50_0_bound[[1]],upper_60_0_bound[[1]],upper_70_0_bound[[1]],upper_80_0_bound[[1]],upper_90_0_bound[[1]]))
names(all_samples_dataframe)=c("decade_order","mean","lower_CI","upper_CI")
```

```{r}
###################
mycolors2=brewer.pal(11, "Spectral")
####plotting all individuals 
pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures/HCHS_SOL_Mexican_PI_NAM_ancestry_migrant_us_born_within_gens_ALL_with_CI_072219_new_figure3a.pdf",height=2.25,width=2.375,pointsize=10)
par(mar=c(2.1,2.1,0.3,0.1))
plot(1,1,type='n',xlim=c(1,7),ylim=c(0.295,0.31),xlab="",ylab="",xaxt='n',yaxt='n')
axis(side=1,padj=-2,cex.axis=0.7,at=1:7, labels=c("30s","40s","50s","60s","70s","80s","90s")) 
axis(side=2,padj=1.5,cex.axis=0.7)
mtext(side=1,"Decades",line=1.1)
mtext(side=2,expression(pi~"of Amerindigenous ancestry"),line=1.1)
abline(h=seq(0.295,0.31,by=0.0025),col=rgb(0,0,0,0.1))
abline(v=seq(0,6,by=1),col=rgb(0,0,0,0.1))
legend("bottomleft",legend=c("All","US born-US born","US born-Not US born","Not US born-Not US born"), col=c(mycolors2[11],mycolors2[1],mycolors2[10],mycolors2[8]),lty=1,lwd=1,bg="white",cex=0.5)
#all samples 
points(means_all_samples_within_gens,pch=19,type="b",col=mycolors2[11])
polygon(c(all_samples_dataframe$decade_order,rev(all_samples_dataframe$decade_order)),c(all_samples_dataframe$upper_CI,rev(all_samples_dataframe$lower_CI)),col=adjustcolor(mycolors2[11], alpha.f = 0.20), border = NA)
#us born to migrant 
points(means_all_us_born_migrant_within_gens,pch=19,type="b",col=mycolors2[10])
polygon(c(us_born_migrant_dataframe$decade_order,rev(us_born_migrant_dataframe$decade_order)),c(us_born_migrant_dataframe$upper_CI,rev(us_born_migrant_dataframe$lower_CI)),col=adjustcolor(mycolors2[10], alpha.f = 0.20), border = NA)
#migrant migrant
points(means_all_migrant_migrant_within_gens,pch=19,type="b",col=mycolors2[8])
polygon(c(migrant_migrant_dataframe$decade_order,rev(migrant_migrant_dataframe$decade_order)),c(migrant_migrant_dataframe$upper_CI,rev(migrant_migrant_dataframe$lower_CI)),col=adjustcolor(mycolors2[8], alpha.f = 0.20), border = NA)
#us born us born
points(means_all_us_born_us_born_within_gens,pch=19,type="b",col=mycolors2[1])
polygon(c(us_born_us_born_dataframe$decade_order,rev(us_born_us_born_dataframe$decade_order)),c(us_born_us_born_dataframe$upper_CI,rev(us_born_us_born_dataframe$lower_CI)),col=adjustcolor(mycolors2[1], alpha.f = 0.20), border = NA)
dev.off()

```