---
title: "New supplementary figure 8"
author: "Melissa Spear"
date: "04/06/2020"
output: html_document
---

Plotting supplementary figure 8. The following script plots 3 separate panels that were pasted together in keynote for prgnaizational purposes 

#Plot of sums of all tracts in MB

```{r}
#Importing in the BED files for the Mexicans 
all_roh<-read.table("/Volumes/LaCie/Downloads/HCHS_SOL_95admixed_Mexicans_ROH_calls.txt", header=T,sep='\t')

d = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T,sep='\t')
pheno_subsetted<-subset(d,select=c("V1","V2","US_BORN","estimated_birth_year","WEIGHT_FINAL_NORM_OVERALL"))

#some individuals do not have ROH so need to add 1 BP for plotting purposes 
all_roh$ROH_A = all_roh$ROH_A+1
all_roh$ROH_B = all_roh$ROH_B+1
all_roh$ROH_C = all_roh$ROH_C+1


all_roh$ROH_A_Mb = all_roh$ROH_A/1000000
all_roh$ROH_B_Mb = all_roh$ROH_B/1000000
all_roh$ROH_C_Mb = all_roh$ROH_C/1000000


all_roh_with_pheno<-merge(all_roh,pheno_subsetted,by.x=("ID"),by.y=c("V2"))
#creating new variable summing three ROH columns 

all_roh_with_pheno$ROH_sums<- rowSums(all_roh_with_pheno[,c("ROH_A_Mb", "ROH_B_Mb","ROH_C_Mb")])
```

```{r}
mexicans_1930s_all<-all_roh_with_pheno[which(all_roh_with_pheno$estimated_birth_year<1940),]
mexicans_1930s_all$Decade ="1930s"

mexicans_1940s_all<-all_roh_with_pheno[which(all_roh_with_pheno$estimated_birth_year>=1940 & all_roh_with_pheno$estimated_birth_year<1950),]
mexicans_1940s_all$Decade ="1940s"

mexicans_1950s_all<-all_roh_with_pheno[which(all_roh_with_pheno$estimated_birth_year>=1950 & all_roh_with_pheno$estimated_birth_year<1960),]
mexicans_1950s_all$Decade ="1950s"

mexicans_1960s_all<-all_roh_with_pheno[which(all_roh_with_pheno$estimated_birth_year>=1960 & all_roh_with_pheno$estimated_birth_year<1970),]
mexicans_1960s_all$Decade ="1960s"

mexicans_1970s_all<-all_roh_with_pheno[which(all_roh_with_pheno$estimated_birth_year>=1970 & all_roh_with_pheno$estimated_birth_year<1980),]
mexicans_1970s_all$Decade ="1970s"

mexicans_1980s_all<-all_roh_with_pheno[which(all_roh_with_pheno$estimated_birth_year>=1980 & all_roh_with_pheno$estimated_birth_year<1990),]
mexicans_1980s_all$Decade ="1980s"

mexicans_1990s_all<-all_roh_with_pheno[which(all_roh_with_pheno$estimated_birth_year>=1990),]
mexicans_1990s_all$Decade ="1990s"

#mexicans_with_decades_all<-rbind(mexicans_1930s_all,mexicans_1940s_all,mexicans_1950s_all,mexicans_1960s_all,mexicans_1970s_all,mexicans_1980s_all,mexicans_1990s_all)

```

```{r}
library("ggplot2")
library(vioplot)
require(RColorBrewer)
pcol=brewer.pal(9, "Set1")

####Plotting the vioplot for all ROH, not jsut Native american regions 
pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures/supplementary_figure8_panelA.pdf",height=2.00,width=6.0,pointsize=10)
par(mfrow=c(1,4), mai = c(0.25, 0.25, 0.2, 0.1))
vioplot(mexicans_1930s_all$ROH_sums,mexicans_1940s_all$ROH_sums,mexicans_1950s_all$ROH_sums,mexicans_1960s_all$ROH_sums,mexicans_1970s_all$ROH_sums,mexicans_1980s_all$ROH_sums,mexicans_1990s_all$ROH_sums,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#1B9E77",xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,1000))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.6)
mtext(side=1,"Decades",line=1.3,cex.lab=0.30)
mtext(side=2,"Total ROH (Mbps)",line=1.1,cex.lab=0.30)
abline(h=seq(0,1000,by=100),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Small ROH 
vioplot(mexicans_1930s_all$ROH_A_Mb,mexicans_1940s_all$ROH_A_Mb,mexicans_1950s_all$ROH_A_Mb,mexicans_1960s_all$ROH_A_Mb,mexicans_1970s_all$ROH_A_Mb,mexicans_1980s_all$ROH_A_Mb,mexicans_1990s_all$ROH_A_Mb,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#D95F02",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,200))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.90)
mtext(side=1,"Decades",line=1.3,cex.axis=0.50)
mtext(side=2,"Total small ROH (Mbps)",line=1.1,cex.lab=0.50)
abline(h=seq(0,200,by=50),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Medium ROH
vioplot(mexicans_1930s_all$ROH_B_Mb,mexicans_1940s_all$ROH_B_Mb,mexicans_1950s_all$ROH_B_Mb,mexicans_1960s_all$ROH_B_Mb,mexicans_1970s_all$ROH_B_Mb,mexicans_1980s_all$ROH_B_Mb,mexicans_1990s_all$ROH_B_Mb,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#7570B3",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,200))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.50)
mtext(side=1,"Decades",line=1.3,cex.lab=0.50)
mtext(side=2,"Total medium ROH (Mbps)",line=1.1,cex.lab=0.50)
abline(h=seq(0,200,by=50),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Long ROH
vioplot(mexicans_1930s_all$ROH_C_Mb,mexicans_1940s_all$ROH_C_Mb,mexicans_1950s_all$ROH_C_Mb,mexicans_1960s_all$ROH_C_Mb,mexicans_1970s_all$ROH_C_Mb,mexicans_1980s_all$ROH_C_Mb,mexicans_1990s_all$ROH_C_Mb,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#E7298A",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,800))
axis(side=1,padj=-2,cex.axis=0.60,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.50)
mtext(side=1,"Decades",line=1.3,cex.lab=0.50)
mtext(side=2,"Total long ROH (Mbps)",line=1.1,cex.lab=0.50)
abline(h=seq(0,800,by=100),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))
dev.off()

```


###############################################
#Panel B - Plot of sum of AI tracts in MB

```{r}
#read in summed AI ROH calls 
ai_roh_calls<-read.table("/Volumes/LaCie/Downloads/split_roh_files/NAM_ROH_segments/reclassified_classes/summed_calls2/HCHS_SOL_Mexicans_alldecades_summed_NAM_ROH_calls_newclasses_080519.txt",header=F,sep='\t')

#adding column titles 
names(ai_roh_calls)=c("IID","ROH_A","ROH_B","ROH_C")

#some samples do not have roh in some classes and will cause errors in the analysis pipeline so added roh of 1 BP long to all samples to fill in 0s.  
ai_roh_calls$ROH_A<-ai_roh_calls$ROH_A+1
ai_roh_calls$ROH_B<-ai_roh_calls$ROH_B+1
ai_roh_calls$ROH_C<-ai_roh_calls$ROH_C+1

#New column of bp to Mbp
ai_roh_calls$ROH_A_Mb = ai_roh_calls$ROH_A/1000000
ai_roh_calls$ROH_B_Mb = ai_roh_calls$ROH_B/1000000
ai_roh_calls$ROH_C_Mb = ai_roh_calls$ROH_C/1000000

#merge with pheno file 
ai_roh_with_pheno<-merge(ai_roh_calls,pheno_subsetted,by.x=("IID"),by.y=c("V2"))

#sum of ROH classes 
ai_roh_with_pheno$ROH_sums<- rowSums(ai_roh_with_pheno[,c("ROH_A_Mb", "ROH_B_Mb","ROH_C_Mb")])
```


```{r}
mexicans_1930s_ai<-ai_roh_with_pheno[which(ai_roh_with_pheno$estimated_birth_year<1940),]
mexicans_1930s_ai$Decade ="1930s"

mexicans_1940s_ai<-ai_roh_with_pheno[which(ai_roh_with_pheno$estimated_birth_year>=1940 & ai_roh_with_pheno$estimated_birth_year<1950),]
mexicans_1940s_ai$Decade ="1940s"

mexicans_1950s_ai<-ai_roh_with_pheno[which(ai_roh_with_pheno$estimated_birth_year>=1950 & ai_roh_with_pheno$estimated_birth_year<1960),]
mexicans_1950s_ai$Decade ="1950s"

mexicans_1960s_ai<-ai_roh_with_pheno[which(ai_roh_with_pheno$estimated_birth_year>=1960 & ai_roh_with_pheno$estimated_birth_year<1970),]
mexicans_1960s_ai$Decade ="1960s"

mexicans_1970s_ai<-ai_roh_with_pheno[which(ai_roh_with_pheno$estimated_birth_year>=1970 & ai_roh_with_pheno$estimated_birth_year<1980),]
mexicans_1970s_ai$Decade ="1970s"

mexicans_1980s_ai<-ai_roh_with_pheno[which(ai_roh_with_pheno$estimated_birth_year>=1980 & ai_roh_with_pheno$estimated_birth_year<1990),]
mexicans_1980s_ai$Decade ="1980s"

mexicans_1990s_ai<-ai_roh_with_pheno[which(ai_roh_with_pheno$estimated_birth_year>=1990),]
mexicans_1990s_ai$Decade ="1990s"

```


```{r}
####Plotting the vioplot for ai ROH, not jsut Native american regions 
pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures/supplementary_figure8_panelB.pdf",height=2.00,width=6.0,pointsize=10)
par(mfrow=c(1,4), mai = c(0.25, 0.25, 0.2, 0.1))
vioplot(mexicans_1930s_ai$ROH_sums,mexicans_1940s_ai$ROH_sums,mexicans_1950s_ai$ROH_sums,mexicans_1960s_ai$ROH_sums,mexicans_1970s_ai$ROH_sums,mexicans_1980s_ai$ROH_sums,mexicans_1990s_ai$ROH_sums,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#1B9E77",xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,1000))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.6)
mtext(side=1,"Decades",line=1.3,cex.lab=0.30)
mtext(side=2,"Total AI ROH (Mbps)",line=1.1,cex.lab=0.30)
abline(h=seq(0,1000,by=100),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Small ROH 
vioplot(mexicans_1930s_ai$ROH_A_Mb,mexicans_1940s_ai$ROH_A_Mb,mexicans_1950s_ai$ROH_A_Mb,mexicans_1960s_ai$ROH_A_Mb,mexicans_1970s_ai$ROH_A_Mb,mexicans_1980s_ai$ROH_A_Mb,mexicans_1990s_ai$ROH_A_Mb,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#D95F02",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,200))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.90)
mtext(side=1,"Decades",line=1.3,cex.axis=0.50)
mtext(side=2,"Total small AI ROH (Mbps)",line=1.1,cex.lab=0.50)
abline(h=seq(0,200,by=50),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Medium ROH
vioplot(mexicans_1930s_ai$ROH_B_Mb,mexicans_1940s_ai$ROH_B_Mb,mexicans_1950s_ai$ROH_B_Mb,mexicans_1960s_ai$ROH_B_Mb,mexicans_1970s_ai$ROH_B_Mb,mexicans_1980s_ai$ROH_B_Mb,mexicans_1990s_ai$ROH_B_Mb,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#7570B3",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,200))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.50)
mtext(side=1,"Decades",line=1.3,cex.lab=0.50)
mtext(side=2,"Total medium AI ROH (Mbps)",line=1.1,cex.lab=0.50)
abline(h=seq(0,200,by=50),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Long ROH
vioplot(mexicans_1930s_ai$ROH_C_Mb,mexicans_1940s_ai$ROH_C_Mb,mexicans_1950s_ai$ROH_C_Mb,mexicans_1960s_ai$ROH_C_Mb,mexicans_1970s_ai$ROH_C_Mb,mexicans_1980s_ai$ROH_C_Mb,mexicans_1990s_ai$ROH_C_Mb,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#E7298A",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,800))
axis(side=1,padj=-2,cex.axis=0.60,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.50)
mtext(side=1,"Decades",line=1.3,cex.lab=0.50)
mtext(side=2,"Total long AI ROH (Mbps)",line=1.1,cex.lab=0.50)
abline(h=seq(0,800,by=100),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))
dev.off()
```


###############################################
#Panel C - Plot of normalized AI tracts in BP 

```{r}
#Read in the admixture file estimates file 
HCHS_SOL_admixture_file<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.3.Q", header =F, sep = ' ')
names(HCHS_SOL_admixture_file) <- c("YRI","CEU","AI")

#Reading in the fam file accompaniment of the .bed file called for the admixture run 
fam_file = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_clean_set_with_Reich_NAM_CEU_YRI_hg19_FINAL_030718_forwardstrand_PRUNED.fam", header=F, sep = ' ')
names(fam_file)<-c("FID","IID","PID","MID","Sex","Pheno")
fam_file_with_IDs <- cbind(fam_file, HCHS_SOL_admixture_file)

##merge with admixture estimates 
ai_roh_with_pheno_admixture<-merge(ai_roh_with_pheno,fam_file_with_IDs, by.x=c("IID"),by.y=c("IID"))

#Calcualting AI genome length 
ai_roh_with_pheno_admixture$AI_both_haps_length<- (ai_roh_with_pheno_admixture$AI * 5563642548)
```

```{r}
#creating new variable summing three ROH columns 
ai_roh_with_pheno_admixture$ROH_allclasses_sums<- rowSums(ai_roh_with_pheno_admixture[,c("ROH_A", "ROH_B","ROH_C")])

#normalizing ALL ROH by global ancestry 
ai_roh_with_pheno_admixture$ROH_allclasses_sums_NORM<-(ai_roh_with_pheno_admixture$ROH_allclasses_sums)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

#normalizing short ROH by global ancestry 
ai_roh_with_pheno_admixture$ROH_A_NORM<-(ai_roh_with_pheno_admixture$ROH_A)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

#normalizing medium ROH by global ancestry 
ai_roh_with_pheno_admixture$ROH_B_NORM<-(ai_roh_with_pheno_admixture$ROH_B)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

#normalizing long ROH by global ancestry
ai_roh_with_pheno_admixture$ROH_C_NORM<-(ai_roh_with_pheno_admixture$ROH_C)/((ai_roh_with_pheno_admixture$AI_both_haps_length)/(2)) 

```


```{r}
mexicans_1930s<-ai_roh_with_pheno_admixture[which(ai_roh_with_pheno_admixture$estimated_birth_year<1940),]
mexicans_1930s$Decade ="1930s"

mexicans_1940s<-ai_roh_with_pheno_admixture[which(ai_roh_with_pheno_admixture$estimated_birth_year>=1940 & ai_roh_with_pheno_admixture$estimated_birth_year<1950),]
mexicans_1940s$Decade ="1940s"

mexicans_1950s<-ai_roh_with_pheno_admixture[which(ai_roh_with_pheno_admixture$estimated_birth_year>=1950 & ai_roh_with_pheno_admixture$estimated_birth_year<1960),]
mexicans_1950s$Decade ="1950s"

mexicans_1960s<-ai_roh_with_pheno_admixture[which(ai_roh_with_pheno_admixture$estimated_birth_year>=1960 & ai_roh_with_pheno_admixture$estimated_birth_year<1970),]
mexicans_1960s$Decade ="1960s"

mexicans_1970s<-ai_roh_with_pheno_admixture[which(ai_roh_with_pheno_admixture$estimated_birth_year>=1970 & ai_roh_with_pheno_admixture$estimated_birth_year<1980),]
mexicans_1970s$Decade ="1970s"

mexicans_1980s<-ai_roh_with_pheno_admixture[which(ai_roh_with_pheno_admixture$estimated_birth_year>=1980 & ai_roh_with_pheno_admixture$estimated_birth_year<1990),]
mexicans_1980s$Decade ="1980s"

mexicans_1990s<-ai_roh_with_pheno_admixture[which(ai_roh_with_pheno_admixture$estimated_birth_year>=1990),]
mexicans_1990s$Decade ="1990s"

```



```{r}
pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures/supplementary_figure8_panelC.pdf",height=2.00,width=6.0,pointsize=10)
par(mfrow=c(1,4), mai = c(0.25, 0.4, 0.2, 0.1))
vioplot(mexicans_1930s$ROH_allclasses_sums_NORM,mexicans_1940s$ROH_allclasses_sums_NORM,mexicans_1950s$ROH_allclasses_sums_NORM,mexicans_1960s$ROH_allclasses_sums_NORM,mexicans_1970s$ROH_allclasses_sums_NORM,mexicans_1980s$ROH_allclasses_sums_NORM,mexicans_1990s$ROH_allclasses_sums_NORM,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#1B9E77",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,0.7))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.90)
mtext(side=1,"Decades",line=1.3,cex.lab=0.3)
mtext(side=2,"Proportion of genome covered",line=2.2,cex.lab=0.3)
mtext(side=2,"by Total AI ROH",line=1,cex.lab=0.3)
abline(h=seq(0,0.7,by=0.1),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Small ROH 
vioplot(mexicans_1930s$ROH_A_NORM,mexicans_1940s$ROH_A_NORM,mexicans_1950s$ROH_A_NORM,mexicans_1960s$ROH_A_NORM,mexicans_1970s$ROH_A_NORM,mexicans_1980s$ROH_A_NORM,mexicans_1990s$ROH_A_NORM,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#D95F02",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,0.1))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.90)
mtext(side=1,"Decades",line=1.3,cex.lab=0.3)
mtext(side=2,"Proportion of genome covered",line=2.2,cex.lab=0.3)
mtext(side=2,"by Small AI ROH",line=1,cex.lab=0.3)
abline(h=seq(0,0.1,by=0.01),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Medium ROH
vioplot(mexicans_1930s$ROH_B_NORM,mexicans_1940s$ROH_B_NORM,mexicans_1950s$ROH_B_NORM,mexicans_1960s$ROH_B_NORM,mexicans_1970s$ROH_B_NORM,mexicans_1980s$ROH_B_NORM,mexicans_1990s$ROH_B_NORM,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#7570B3",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,0.1))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.90)
mtext(side=1,"Decades",line=1.3,cex.lab=0.3)
mtext(side=2,"Proportion of genome covered",line=2.2,cex.lab=0.3)
mtext(side=2,"by Medium AI ROH",line=1,cex.lab=0.3)
abline(h=seq(0,0.1,by=0.01),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))

#Long ROH
vioplot(mexicans_1930s$ROH_C_NORM,mexicans_1940s$ROH_C_NORM,mexicans_1950s$ROH_C_NORM,mexicans_1960s$ROH_C_NORM,mexicans_1970s$ROH_C_NORM,mexicans_1980s$ROH_C_NORM,mexicans_1990s$ROH_C_NORM,  names=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"), 
        col="#E7298A",cex.axis=0.60,cex.lab=0.9,xlab="",ylab="",xaxt='n',yaxt='n',ylim=c(0,0.7))
axis(side=1,padj=-2,cex.axis=0.60,cex.lab=0.90,at=c('1','2','3','4','5','6','7'), labels=c("1930s","1940s","1950s","1960s","1970s","1980s","1990s"))
axis(side=2,padj=1.5,cex.axis=0.60,cex.lab=0.90)
mtext(side=1,"Decades",line=1.3,cex.lab=0.3)
mtext(side=2,"Proportion of genome covered",line=2.2,cex.lab=0.3)
mtext(side=2,"by Long AI ROH",line=1,cex.lab=0.3)
abline(h=seq(0,0.7,by=0.1),col=rgb(0,0,0,0.1))
abline(v=seq(1,7,by=1),col=rgb(0,0,0,0.1))
dev.off()


```


