---
title: "supplementary table 3"
author: "Melissa Spear"
date: "21/07/2020"
output: html_document
---



```{r}
#Height over time
b = read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T, sep='\t')

a = b[which(a$V2 != "WG0228238-DNAG09"),]

###Stratified height plots
a$CENTER2=as.factor(a$CENTER)

#breaking up by the quartiles of NAM ancestry 
Lowest_NAM=a[which(a$NAM>=0.01 & a$NAM<0.37),]
Lower_NAM=a[which(a$NAM>=0.37 & a$NAM<0.46),]
Moderate_NAM=a[which(a$NAM>=0.46 & a$NAM<=0.58),]
High_NAM=a[which(a$NAM>0.58),]


Lowest_NAM$native_level="4"
Lower_NAM$native_level="3"
Moderate_NAM$native_level="2"
High_NAM$native_level="1"

all_levels=rbind(Lowest_NAM,Lower_NAM,Moderate_NAM,High_NAM)

```

```{r}
#Multiple regression models 
Lowest_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=Lowest_NAM)
Lower_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=Lower_NAM)
Moderate_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=Moderate_NAM)
High_model_center=lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=High_NAM)
all_groups_center <- lm(HEIGHT~estimated_birth_year+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2,data=all_levels)
```

```{r}
##Creating the different rows of each table.

Height_table_all<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
Height_table_all[1,1]<-"All"
Height_table_all[1,2]<-"Birth year"
Height_table_all[1,3]<-(summary(all_groups_center)$df[2]) + 5
Height_table_all[1,4]<-summary(all_groups_center)$r.squared
Height_table_all[1,5]<-summary(all_groups_center)$coeff[2,1]
Height_table_all[1,6]<-summary(all_groups_center)$coeff[2,2]
Height_table_all[1,7]<-summary(all_groups_center)$coeff[2,4]

Height_table_High<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
Height_table_High[1,1]<-"AI>0.58"
Height_table_High[1,2]<-"Birth year"
Height_table_High[1,3]<-(summary(High_model_center)$df[2]) + 5
Height_table_High[1,4]<-summary(High_model_center)$r.squared
Height_table_High[1,5]<-summary(High_model_center)$coeff[2,1]
Height_table_High[1,6]<-summary(High_model_center)$coeff[2,2]
Height_table_High[1,7]<-summary(High_model_center)$coeff[2,4]

Height_table_Moderate<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
Height_table_Moderate[1,1]<-"0.46<=AI<=0.58"
Height_table_Moderate[1,2]<-"Birth year"
Height_table_Moderate[1,3]<-(summary(Moderate_model_center)$df[2]) + 5
Height_table_Moderate[1,4]<-summary(Moderate_model_center)$r.squared
Height_table_Moderate[1,5]<-summary(Moderate_model_center)$coeff[2,1]
Height_table_Moderate[1,6]<-summary(Moderate_model_center)$coeff[2,2]
Height_table_Moderate[1,7]<-summary(Moderate_model_center)$coeff[2,4]

Height_table_Lower<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
Height_table_Lower[1,1]<-"0.37<=AI<0.46"
Height_table_Lower[1,2]<-"Birth year"
Height_table_Lower[1,3]<-(summary(Lower_model_center)$df[2]) + 5
Height_table_Lower[1,4]<-summary(Lower_model_center)$r.squared
Height_table_Lower[1,5]<-summary(Lower_model_center)$coeff[2,1]
Height_table_Lower[1,6]<-summary(Lower_model_center)$coeff[2,2]
Height_table_Lower[1,7]<-summary(Lower_model_center)$coeff[2,4]

Height_table_Lowest<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
Height_table_Lowest[1,1]<-"AI<0.37"
Height_table_Lowest[1,2]<-"Birth year"
Height_table_Lowest[1,3]<-(summary(Lowest_model_center)$df[2]) + 5
Height_table_Lowest[1,4]<-summary(Lowest_model_center)$r.squared
Height_table_Lowest[1,5]<-summary(Lowest_model_center)$coeff[2,1]
Height_table_Lowest[1,6]<-summary(Lowest_model_center)$coeff[2,2]
Height_table_Lowest[1,7]<-summary(Lowest_model_center)$coeff[2,4]


all_height_over_time<-rbind(Height_table_all,Height_table_High,Height_table_Moderate,Height_table_Lower,Height_table_Lowest)

all_height_over_time
```