---
title: "Untitled"
author: "Melissa Spear & Alex Diaz-Papkovich"
date: "02/09/2020"
output: html_document
---

```{r}
##################################################################
#Observed height vs predicted height 
pheno_file<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T, sep='\t')

PRS_phys<-read.table("/Volumes/LaCie/Downloads/PRS/HCHS_SOLMexicans_090120_UKBB_snps_individual_polygenic_height_scores_phys_distance_1Mb_filter_TEST2.txt")
names(PRS_phys)<-c("FID","IID","risk_score")
merged_data_phys<-merge(PRS_phys,pheno_file,by.x=("FID"),by.y=c("V1"))

#setting "Center" variable as factor so R knows how to use it in model 
merged_data_phys$CENTER2<-as.factor(merged_data_phys$CENTER)

merged_data_phys$Education<-as.factor(merged_data_phys$EDUCATION_C3)

merged_data_phys$num_us_parents <- with(merged_data_phys,
                         ifelse(PIEA14=='63' & PIEA11=='63',2,
                            ifelse(PIEA14!='63' & PIEA11!='63',0,1)))
merged_data_phys$num_us_parents<-as.numeric(merged_data_phys$num_us_parents)

#Dividing dataset 
Lowest_NAM <- merged_data_phys[which(merged_data_phys$NAM>=0.01 & merged_data_phys$NAM<0.37),]
Lower_NAM <- merged_data_phys[which(merged_data_phys$NAM>=0.37 & merged_data_phys$NAM<0.46),]
Moderate_NAM <- merged_data_phys[which(merged_data_phys$NAM>=0.46 & merged_data_phys$NAM<=0.58),]
High_NAM <- merged_data_phys[which(merged_data_phys$NAM>0.58),]

all_levels<-rbind(Lowest_NAM,Lower_NAM,Moderate_NAM,High_NAM)

```

```{r}
Lowest_model_center_height <- lm(risk_score~HEIGHT+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2+ Education + US_BORN + num_us_parents,data=Lowest_NAM)
Lower_model_center_height <- lm(risk_score~HEIGHT+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=Lower_NAM)
Moderate_model_center_height <- lm(risk_score~HEIGHT+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=Moderate_NAM)
High_model_center_height <- lm(risk_score~HEIGHT+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=High_NAM)
all_model_center_height <- lm(risk_score~HEIGHT+GENDERNUM+log(WEIGHT_FINAL_NORM_OVERALL)+CENTER2 + Education + US_BORN + num_us_parents,data=all_levels)
```

```{r}

##Creating the different rows of each table.

PRS_Height_table_all<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
PRS_Height_table_all[1,1]<-"All"
PRS_Height_table_all[1,2]<-"Observed Height"
PRS_Height_table_all[1,3]<-(summary(all_model_center_height)$df[2]) + 5
PRS_Height_table_all[1,4]<-summary(all_model_center_height)$r.squared
PRS_Height_table_all[1,5]<-summary(all_model_center_height)$coeff[2,1]
PRS_Height_table_all[1,6]<-summary(all_model_center_height)$coeff[2,2]
PRS_Height_table_all[1,7]<-summary(all_model_center_height)$coeff[2,4]

PRS_Height_table_High<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
PRS_Height_table_High[1,1]<-"AI>0.58"
PRS_Height_table_High[1,2]<-"Observed Height"
PRS_Height_table_High[1,3]<-(summary(High_model_center_height)$df[2]) + 5
PRS_Height_table_High[1,4]<-summary(High_model_center_height)$r.squared
PRS_Height_table_High[1,5]<-summary(High_model_center_height)$coeff[2,1]
PRS_Height_table_High[1,6]<-summary(High_model_center_height)$coeff[2,2]
PRS_Height_table_High[1,7]<-summary(High_model_center_height)$coeff[2,4]

PRS_Height_table_Moderate<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
PRS_Height_table_Moderate[1,1]<-"0.46<=AI<=0.58"
PRS_Height_table_Moderate[1,2]<-"Observed Height"
PRS_Height_table_Moderate[1,3]<-(summary(Moderate_model_center_height)$df[2]) + 5
PRS_Height_table_Moderate[1,4]<-summary(Moderate_model_center_height)$r.squared
PRS_Height_table_Moderate[1,5]<-summary(Moderate_model_center_height)$coeff[2,1]
PRS_Height_table_Moderate[1,6]<-summary(Moderate_model_center_height)$coeff[2,2]
PRS_Height_table_Moderate[1,7]<-summary(Moderate_model_center_height)$coeff[2,4]

PRS_Height_table_Lower<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
PRS_Height_table_Lower[1,1]<-"0.37<=AI<0.46"
PRS_Height_table_Lower[1,2]<-"Observed Height"
PRS_Height_table_Lower[1,3]<-(summary(Lower_model_center_height)$df[2]) + 5
PRS_Height_table_Lower[1,4]<-summary(Lower_model_center_height)$r.squared
PRS_Height_table_Lower[1,5]<-summary(Lower_model_center_height)$coeff[2,1]
PRS_Height_table_Lower[1,6]<-summary(Lower_model_center_height)$coeff[2,2]
PRS_Height_table_Lower[1,7]<-summary(Lower_model_center_height)$coeff[2,4]

PRS_Height_table_Lowest<-setNames(data.frame(matrix(ncol=7, nrow=0)), c("Group","X","N","R2","Effect","Std.Err","P"))
PRS_Height_table_Lowest[1,1]<-"AI<0.37"
PRS_Height_table_Lowest[1,2]<-"Observed Height"
PRS_Height_table_Lowest[1,3]<-(summary(Lowest_model_center_height)$df[2]) + 5
PRS_Height_table_Lowest[1,4]<-summary(Lowest_model_center_height)$r.squared
PRS_Height_table_Lowest[1,5]<-summary(Lowest_model_center_height)$coeff[2,1]
PRS_Height_table_Lowest[1,6]<-summary(Lowest_model_center_height)$coeff[2,2]
PRS_Height_table_Lowest[1,7]<-summary(Lowest_model_center_height)$coeff[2,4]

all_prs_height_tables2<-rbind(PRS_Height_table_all,PRS_Height_table_High,PRS_Height_table_Moderate,PRS_Height_table_Lower,PRS_Height_table_Lowest)

all_prs_height_tables2
```

All
```{r}
0.003736 - (1.96*0.000699)
0.003736 + (1.96*0.000699)
```


AI>0.58
```{r}
0.002525 - (1.96*0.019527)
0.002525 + (1.96*0.019527)
```


0.46<=AI<=0.58	
```{r}
0.12438 - (1.96*0.0180757)
0.12438 + (1.96*0.0180757)
```


0.37<=AI<0.46	
```{r}
0.006109 - (1.96*0.0014869)
0.006109 + (1.96*0.0014869)
```


AI<0.37	
```{r}
0.004898 - (1.96*0.001388)
0.004898 + (1.96*0.001388)
```

