---
title: "supplementary figure 9b"
author: "Melissa Spear"
date: "29/07/2020"
output: html_document
---

The following investigates assortative mating in parents of US born vs not US born HCHS/SOL individuals 
```{r}
Mexican_reclassified<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T,sep='\t')
```

Read in assortative mating data 
```{r}
assor_mating=read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_with_parents_global_ancestry_estimates.txt",header=T,sep='\t')

assor_mating_subset<-subset(assor_mating,select=c("IID","NAM","Parent1_NAM","Parent2_NAM"))
```

Merge data and rename variables 
```{r}
mexicans_assor_data<-merge(Mexican_reclassified,assor_mating_subset,by.x=c("V2"),by.y=c("IID"))

mexicans_assor_data_subset=subset(mexicans_assor_data,select=c("V2","NAM.x","estimated_birth_year","US_BORN","Parent1_NAM","Parent2_NAM"))

names(mexicans_assor_data_subset)=c("IID","AI","estimated_birth_year","US_BORN","Parent1_AI","Parent2_AI")
```

Finding absolute difference between AI ancestry of parents a
```{r}
mexicans_assor_data_subset$Parental_AI_Diff<-abs(mexicans_assor_data_subset$Parent1_AI - mexicans_assor_data_subset$Parent2_AI)
```


```{r}
#subset into us born and non us born
us_born<-mexicans_assor_data_subset[which(mexicans_assor_data_subset$US_BORN=='1'),]
#not_us_born<-mexicans_assor_data_subset[which(mexicans_assor_data_subset$US_BORN=='0'),]
```


US Born decade breakdown
```{r}
mexicans_1930s_us_born<-us_born[which(us_born$estimated_birth_year<1940),]
mexicans_1930s_us_born$Decade ="1930"

mexicans_1940s_us_born<-us_born[which(us_born$estimated_birth_year>=1940 & us_born$estimated_birth_year<1950),]
mexicans_1940s_us_born$Decade ="1940"

mexicans_1950s_us_born<-us_born[which(us_born$estimated_birth_year>=1950 & us_born$estimated_birth_year<1960),]
mexicans_1950s_us_born$Decade ="1950"

mexicans_1960s_us_born<-us_born[which(us_born$estimated_birth_year>=1960 & us_born$estimated_birth_year<1970),]
mexicans_1960s_us_born$Decade ="1960"

mexicans_1970s_us_born<-us_born[which(us_born$estimated_birth_year>=1970 & us_born$estimated_birth_year<1980),]
mexicans_1970s_us_born$Decade ="1970"

mexicans_1980s_us_born<-us_born[which(us_born$estimated_birth_year>=1980 & us_born$estimated_birth_year<1990),]
mexicans_1980s_us_born$Decade ="1980"

mexicans_1990s_us_born<-us_born[which(us_born$estimated_birth_year>=1990),]
mexicans_1990s_us_born$Decade ="1990"

mexicans_all_us_born<-rbind(mexicans_1930s_us_born,mexicans_1940s_us_born,mexicans_1950s_us_born,mexicans_1960s_us_born,mexicans_1970s_us_born,mexicans_1980s_us_born,mexicans_1990s_us_born)
```


Correlation of US born samples 
```{r}
#1930s 
cor_1930s_us_born<-cor.test(mexicans_1930s_us_born$Parent1_AI, mexicans_1930s_us_born$Parent2_AI)
cor_1930s_us_born
```

```{r}
#1940s 
cor_1940s_us_born<-cor.test(mexicans_1940s_us_born$Parent1_AI, mexicans_1940s_us_born$Parent2_AI)
cor_1940s_us_born
```

```{r}
#1950s 
cor_1950s_us_born<-cor.test(mexicans_1950s_us_born$Parent1_AI, mexicans_1950s_us_born$Parent2_AI)
cor_1950s_us_born
```

```{r}
#1960s 
cor_1960s_us_born<-cor.test(mexicans_1960s_us_born$Parent1_AI, mexicans_1960s_us_born$Parent2_AI)
cor_1960s_us_born
```

```{r}
#1970s 
cor_1970s_us_born<-cor.test(mexicans_1970s_us_born$Parent1_AI, mexicans_1970s_us_born$Parent2_AI)
cor_1970s_us_born
```

```{r}
#1980s 
cor_1980s_us_born<-cor.test(mexicans_1980s_us_born$Parent1_AI, mexicans_1980s_us_born$Parent2_AI)
cor_1980s_us_born
```

```{r}
#1990s 
cor_1990s_us_born<-cor.test(mexicans_1990s_us_born$Parent1_AI, mexicans_1990s_us_born$Parent2_AI)
cor_1990s_us_born
```



Plot supplementary figure 9b 
```{r}
library(ggplot2)
library(ggridges)
require(RColorBrewer)

myColors=brewer.pal(7, "Set1")

#Plotting ridgeline plot
pdf("/Users/melissaspear/Dropbox/HCHS_SOL/paper_figures/supplementary_figure9b.pdf",height=2.375,width=2.55,pointsize=10)
par(mar=c(2.1,2.1,0.1,0.6))
ggplot(mexicans_all_us_born,aes(x=Parental_AI_Diff,y=Decade,fill=factor(Decade))) +
  geom_density_ridges(scale=1)+ theme_bw() + theme(axis.text.x=element_text(size=rel(0.8)),axis.text.y=element_text(size=rel(0.8))) + theme(axis.title.x = element_text(size=10),axis.title.y = element_text(size=10))+
  scale_y_discrete(expand = expand_scale(mult = c(0.01, .2))) + 
 scale_fill_manual(values=c("#E41A1C","#FF7F00","#FFFF33","#4DAF4A","#377EB8","#984EA3","#A65628")) + theme(legend.position = "none") + labs(x="Difference in Parental AI ancestry ", y="Decades")
dev.off()

```