---
title: "Linear Regression of Complex Traits"
author: "Melissa Spear"
date: "04/08/2020"
output: html_document
---

Cleaning each of the variables 
```{r}
Mexicans_pheno<-read.table("/Users/melissaspear/Dropbox/HCHS_SOL/HCHS_SOL_Mexicans_admixed_95_full_pheno_010919.txt",header=T, sep='\t')

Mexicans_pheno$CENTER2<-as.numeric(Mexicans_pheno$CENTER)

# Subsetting out the quantitative traits  
subset_Mexican_pheno<-subset(Mexicans_pheno, select=c("NAM","estimated_birth_year","WEIGHT_FINAL_NORM_OVERALL","GENDERNUM","CENTER2","SLPA92","ABPA1A", "ABPA1B", "ABPA1C", "ABPA1D", "ABPA1E", "ABPA1F","LABA91","HBA1C_SI","MHEA27","PRBA29","BMI","HEIGHT","LABA1","LABA23","LABA24","LABA25","LABA26","LABA27","ANTA4","LABA3","LABA5","LABA9","LABA6","PRBA25","SBPA5","WAIST_HIP","ANTA10A","ANTA10B","EGFRCKD","EGFRMDRD","MENO_C","LABA66","LABA68","LABA67","LABA69","SLPDUR","ECGA8","LABA82","LABA83","LABA84","LABA103","ANTA5","ECGA10","ECGA11","FEV1_FVC_RATIO","ECGA9","ECGA7","LABA10","LABA11","LABA12","LABA13","LABA14","LABA4","LABA7","LABA8","LABA70","LABA71","LABA79","PRBA36","LABA76","LABA2","LABA81","ECGA12","ECGA264","LABA99","SBPA6","LABA72","LABA80"))

#rename all columns
names(subset_Mexican_pheno)<-c("AI","birth_year","WEIGHT_FINAL_NORM_OVERALL","GENDER","CENTER","Mean SpO2","Right brachial systolic blood pressure","Right dorsalis pedis systolic blood pressure","Right posterior tibial systolic blood pressure","Left posterior tibial systolic blood pressure","Left dorsalis pedis systolic blood pressure","Left brachial systolic blood pressure","High-sensitivity C-reactive protein","Glycosylated hemoglobin (HbA1c)","Age at which menses began","FEV1","BMI","HEIGHT","White blood count","Neutrophil count","Lymphocyte count","Monocyte count","Eosinophil count","Basophil count","Weight","Hemoglobin","Mean corpuscular volume","Platelet count","Mean corpuscular hemoglobin","FVC","Average systolic blood pressure","Waist to hip ratio","Waist girth","Hip girth","EGFR CKD Epi","EGFR MDRD","Age at natural menopause","Total cholesterol","HDL cholesterol","Triglycerides","LDL cholesterol","Average sleep duration","Heart rate, ventricular","Iron","Total iron binding capacity","% Transferrin saturation","Ferritin","% Fat","QRS duration","QT duration","FEV1 FVC Ratio","PR duration","Heart rate, atrial","% neutrophils","% Lymphocytes","% Monocytes","% Eosinophils","% Basophils","% Hematocrit","Mean corpuscular hemoglobin concentration","% Red cell distribution width","Glucose, fasting","Glucose, post OGTT","Urine creatinine, random","Predicted FVC","Creatinine","Red blood cell count","Albumin/creatine ratio","QTc calculated","HRV","% Immature granulocytes","Average diastolic blood pressure","% Glycosylated hemoglobin","Urine microalbumin, random")
```

```{r}
fit <- lapply(subset_Mexican_pheno[,6:74], function(x) lm(x ~ AI + birth_year + GENDER + log(WEIGHT_FINAL_NORM_OVERALL) + CENTER, data = subset_Mexican_pheno,na.action = na.omit))
```


```{r}
#Creare empty dataframe to store the results 
pheno_results <- data.frame(pheno = character(),
                            variable = character(),
                               estimate = double(),
                               std.errors = double(),
                               p.vals = double(), stringsAsFactors = FALSE)
```

Create table of regression results for all variables 
```{r}
for (i in 1:length(fit))
{
  #i=1
  testing_summary <- summary(fit[[i]])
  coef_table <- coef(testing_summary)
  #coef_table
  coef_table_vals <- coef_table[which(rownames(coef_table) %in% c("AI","birth_year","GENDER","log(WEIGHT_FINAL_NORM_OVERALL)","CENTER")),
                              which(colnames(coef_table) %in% c("Estimate", "Std. Error","Pr(>|t|)"))]
  test_df <- as.data.frame(coef_table_vals)
  
  # add the covariates to the data frame (they're row names right now)
  test_df$COVARIATE <- rownames(test_df)
  
  # add the phenotype name column
  test_df$PHENO <- as.character(names(fit[i]))
  
  # re-order columns
  test_df <- test_df[,c(5,4,1,2,3)]
  rownames(test_df) <- c() #drop rownames
  
  # re-name columns
  colnames(test_df) <- c("PHENO","COVARIATE","SLOPE","SE","P")
  
  #add results for one trait to final table 
  pheno_results <- rbind(pheno_results, test_df) #this command still keeps the rownames so need to drop 
}
```

Write out the table 
```{r}
#install.packages("xlsx")
library(xlsx)
write.table(pheno_results,"/Users/melissaspear/Dropbox/HCHS_SOL/complex_traits/extended_supplementary_table3_new_090720.txt",row.names=F,col.names=T,sep='\t',quote=F)
#write.xlsx(pheno_results,"/Users/melissaspear/Dropbox/HCHS_SOL/complex_traits/extended_supplementary_table3_new_090720.xlsx")
```



